# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
role_premier = Role.create(name: 'premier')
#user = User.create(first_name: "Admin", last_name: "Premier", email: "admin@iuvare.com.mx", xango_id: "123456", iuvare_id: "999999", active: true, password:"xangoxango", roles: [role_premier])
#Invitation.create(user_id: user.id, recipient_email:"correo@correo.com", token:"cualquiercosa")

#Test de Personalidad
personality_test = Test.create(name: "Test de personalidad", test_type: "percentage", code: "color", instructions: "Piensa en las palabras, en lo que significan y no en lo que te gustaría, realmente piensa cual se asemeja más a ti o con cual te sientes más identificado.")

#FORTALEZAS
pt_first_question = Question.create(test: personality_test, text: "")
pt_q1_answer_1 = Answer.create(question: pt_first_question, text: "Expresivo", answer_type: "red")
pt_q1_answer_2 = Answer.create(question: pt_first_question, text: "Aventurero", answer_type: "yellow")
pt_q1_answer_3 = Answer.create(question: pt_first_question, text: "Analítico", answer_type: "green")
pt_q1_answer_4 = Answer.create(question: pt_first_question, text: "Adaptable", answer_type: "blue")

pt_second_question = Question.create(test: personality_test, text: "")
pt_q2_answer_1 = Answer.create(question: pt_second_question, text: "Bromista", answer_type: "red")
pt_q2_answer_2 = Answer.create(question: pt_second_question, text: "Determinado", answer_type: "yellow")
pt_q2_answer_3 = Answer.create(question: pt_second_question, text: "Puntual", answer_type: "green")
pt_q2_answer_4 = Answer.create(question: pt_second_question, text: "Sereno", answer_type: "blue")

pt_third_question = Question.create(test: personality_test, text: "")
pt_q3_answer_1 = Answer.create(question: pt_third_question, text: "Entusiasta", answer_type: "red")
pt_q3_answer_2 = Answer.create(question: pt_third_question, text: "Decidido", answer_type: "yellow")
pt_q3_answer_3 = Answer.create(question: pt_third_question, text: "Preciso", answer_type: "green")
pt_q3_answer_4 = Answer.create(question: pt_third_question, text: "Introvertido", answer_type: "blue")

pt_fourth_question = Question.create(test: personality_test, text: "")
pt_q4_answer_1 = Answer.create(question: pt_fourth_question, text: "Confías", answer_type: "red")
pt_q4_answer_2 = Answer.create(question: pt_fourth_question, text: "Competitivo", answer_type: "yellow")
pt_q4_answer_3 = Answer.create(question: pt_fourth_question, text: "Artista", answer_type: "green")
pt_q4_answer_4 = Answer.create(question: pt_fourth_question, text: "Considerado", answer_type: "blue")

pt_fifth_question = Question.create(test: personality_test, text: "")
pt_q5_answer_1 = Answer.create(question: pt_fifth_question, text: "Expresivo", answer_type: "red")
pt_q5_answer_2 = Answer.create(question: pt_fifth_question, text: "Diriges", answer_type: "yellow")
pt_q5_answer_3 = Answer.create(question: pt_fifth_question, text: "Reflexivo", answer_type: "green")
pt_q5_answer_4 = Answer.create(question: pt_fifth_question, text: "Reservado", answer_type: "blue")

pt_sixth_question = Question.create(test: personality_test, text: "")
pt_q6_answer_1 = Answer.create(question: pt_sixth_question, text: "Idealista", answer_type: "red")
pt_q6_answer_2 = Answer.create(question: pt_sixth_question, text: "Proactivo", answer_type: "yellow")
pt_q6_answer_3 = Answer.create(question: pt_sixth_question, text: "Metódico", answer_type: "green")
pt_q6_answer_4 = Answer.create(question: pt_sixth_question, text: "Sensible", answer_type: "blue")

pt_seventh_question = Question.create(test: personality_test, text: "")
pt_q7_answer_1 = Answer.create(question: pt_seventh_question, text: "Positivo", answer_type: "red")
pt_q7_answer_2 = Answer.create(question: pt_seventh_question, text: "Desafiante", answer_type: "yellow")
pt_q7_answer_3 = Answer.create(question: pt_seventh_question, text: "Planificador", answer_type: "green")
pt_q7_answer_4 = Answer.create(question: pt_seventh_question, text: "Paciente", answer_type: "blue")

pt_eighth_question = Question.create(test: personality_test, text: "")
pt_q8_answer_1 = Answer.create(question: pt_eighth_question, text: "Espontáneo", answer_type: "red")
pt_q8_answer_2 = Answer.create(question: pt_eighth_question, text: "Seguro de si", answer_type: "yellow")
pt_q8_answer_3 = Answer.create(question: pt_eighth_question, text: "Organizado", answer_type: "green")
pt_q8_answer_4 = Answer.create(question: pt_eighth_question, text: "Cuida a los demás", answer_type: "blue")

pt_ninth_question = Question.create(test: personality_test, text: "")
pt_q9_answer_1 = Answer.create(question: pt_ninth_question, text: "Optimista", answer_type: "red")
pt_q9_answer_2 = Answer.create(question: pt_ninth_question, text: "Jefe", answer_type: "yellow")
pt_q9_answer_3 = Answer.create(question: pt_ninth_question, text: "Ordenado", answer_type: "green")
pt_q9_answer_4 = Answer.create(question: pt_ninth_question, text: "Servicial", answer_type: "blue")

pt_tenth_question = Question.create(test: personality_test, text: "")
pt_q10_answer_1 = Answer.create(question: pt_tenth_question, text: "Persuasivo", answer_type: "red")
pt_q10_answer_2 = Answer.create(question: pt_tenth_question, text: "Enérgico", answer_type: "yellow")
pt_q10_answer_3 = Answer.create(question: pt_tenth_question, text: "Fiel", answer_type: "green")
pt_q10_answer_4 = Answer.create(question: pt_tenth_question, text: "Empático", answer_type: "blue")

pt_eleventh_question = Question.create(test: personality_test, text: "")
pt_q11_answer_1 = Answer.create(question: pt_eleventh_question, text: "Platicador", answer_type: "red")
pt_q11_answer_2 = Answer.create(question: pt_eleventh_question, text: "Osado", answer_type: "yellow")
pt_q11_answer_3 = Answer.create(question: pt_eleventh_question, text: "Disciplinado", answer_type: "green")
pt_q11_answer_4 = Answer.create(question: pt_eleventh_question, text: "Solidario", answer_type: "blue")

pt_twelfth_question = Question.create(test: personality_test, text: "")
pt_q12_answer_1 = Answer.create(question: pt_twelfth_question, text: "Alegre", answer_type: "red")
pt_q12_answer_2 = Answer.create(question: pt_twelfth_question, text: "Directo", answer_type: "yellow")
pt_q12_answer_3 = Answer.create(question: pt_twelfth_question, text: "Cauteloso", answer_type: "green")
pt_q12_answer_4 = Answer.create(question: pt_twelfth_question, text: "Ayuda", answer_type: "blue")

pt_thirteenth_question = Question.create(test: personality_test, text: "")
pt_q13_answer_1 = Answer.create(question: pt_thirteenth_question, text: "Inspirador", answer_type: "red")
pt_q13_answer_2 = Answer.create(question: pt_thirteenth_question, text: "Firme", answer_type: "yellow")
pt_q13_answer_3 = Answer.create(question: pt_thirteenth_question, text: "Piensas mucho", answer_type: "green")
pt_q13_answer_4 = Answer.create(question: pt_thirteenth_question, text: "Cálido", answer_type: "blue")

pt_fourteenth_question = Question.create(test: personality_test, text: "")
pt_q14_answer_1 = Answer.create(question: pt_fourteenth_question, text: "Hospitalario", answer_type: "red")
pt_q14_answer_2 = Answer.create(question: pt_fourteenth_question, text: "Tomas el control", answer_type: "yellow")
pt_q14_answer_3 = Answer.create(question: pt_fourteenth_question, text: "Humor Seco", answer_type: "green")
pt_q14_answer_4 = Answer.create(question: pt_fourteenth_question, text: "Leal", answer_type: "blue")

pt_fifteenth_question = Question.create(test: personality_test, text: "")
pt_q15_answer_1 = Answer.create(question: pt_fifteenth_question, text: "Sociable", answer_type: "red")
pt_q15_answer_2 = Answer.create(question: pt_fifteenth_question, text: "Hacedor", answer_type: "yellow")
pt_q15_answer_3 = Answer.create(question: pt_fifteenth_question, text: "Consistente", answer_type: "green")
pt_q15_answer_4 = Answer.create(question: pt_fifteenth_question, text: "Mediador", answer_type: "blue")

pt_sixteenth_question = Question.create(test: personality_test, text: "")
pt_q16_answer_1 = Answer.create(question: pt_sixteenth_question, text: "Interactúas", answer_type: "red")
pt_q16_answer_2 = Answer.create(question: pt_sixteenth_question, text: "Tenaz", answer_type: "yellow")
pt_q16_answer_3 = Answer.create(question: pt_sixteenth_question, text: "Diplomático", answer_type: "green")
pt_q16_answer_4 = Answer.create(question: pt_sixteenth_question, text: "Tolerante", answer_type: "blue")

pt_seventeenth_question = Question.create(test: personality_test, text: "")
pt_q17_answer_1 = Answer.create(question: pt_seventeenth_question, text: "Vivaz", answer_type: "red")
pt_q17_answer_2 = Answer.create(question: pt_seventeenth_question, text: "Determinante", answer_type: "yellow")
pt_q17_answer_3 = Answer.create(question: pt_seventeenth_question, text: "Perfeccionista", answer_type: "green")
pt_q17_answer_4 = Answer.create(question: pt_seventeenth_question, text: "Sabes escuchar", answer_type: "blue")

pt_eighteenth_question = Question.create(test: personality_test, text: "")
pt_q18_answer_1 = Answer.create(question: pt_eighteenth_question, text: "Amigable", answer_type: "red")
pt_q18_answer_2 = Answer.create(question: pt_eighteenth_question, text: "Atrevido", answer_type: "yellow")
pt_q18_answer_3 = Answer.create(question: pt_eighteenth_question, text: "Estructurado", answer_type: "green")
pt_q18_answer_4 = Answer.create(question: pt_eighteenth_question, text: "Tierno", answer_type: "blue")

pt_nineteenth_question = Question.create(test: personality_test, text: "")
pt_q19_answer_1 = Answer.create(question: pt_nineteenth_question, text: "Popular", answer_type: "red")
pt_q19_answer_2 = Answer.create(question: pt_nineteenth_question, text: "Súper líder", answer_type: "yellow")
pt_q19_answer_3 = Answer.create(question: pt_nineteenth_question, text: "Sistemático", answer_type: "green")
pt_q19_answer_4 = Answer.create(question: pt_nineteenth_question, text: "Agradable", answer_type: "blue")

pt_twentieth_question = Question.create(test: personality_test, text: "")
pt_q20_answer_1 = Answer.create(question: pt_twentieth_question, text: "Feliz", answer_type: "red")
pt_q20_answer_2 = Answer.create(question: pt_twentieth_question, text: "Asertivo", answer_type: "yellow")
pt_q20_answer_3 = Answer.create(question: pt_twentieth_question, text: "Conservador", answer_type: "green")
pt_q20_answer_4 = Answer.create(question: pt_twentieth_question, text: "Tranquilo", answer_type: "blue")

#DEBILIDADES
pt_twentyfirst_question = Question.create(test: personality_test, text: "")
pt_q21_answer_1 = Answer.create(question: pt_twentyfirst_question, text: "Superficial", answer_type: "red")
pt_q21_answer_2 = Answer.create(question: pt_twentyfirst_question, text: "Melancólico", answer_type: "green")
pt_q21_answer_3 = Answer.create(question: pt_twentyfirst_question, text: "Mandón", answer_type: "yellow")
pt_q21_answer_4 = Answer.create(question: pt_twentyfirst_question, text: "Penoso", answer_type: "blue")

pt_twentysecond_question = Question.create(test: personality_test, text: "")
pt_q22_answer_1 = Answer.create(question: pt_twentysecond_question, text: "Indisciplinado", answer_type: "red")
pt_q22_answer_2 = Answer.create(question: pt_twentysecond_question, text: "Rencoroso", answer_type: "green")
pt_q22_answer_3 = Answer.create(question: pt_twentysecond_question, text: "Interrumpes", answer_type: "yellow")
pt_q22_answer_4 = Answer.create(question: pt_twentysecond_question, text: "Apático", answer_type: "blue")

pt_twentythird_question = Question.create(test: personality_test, text: "")
pt_q23_answer_1 = Answer.create(question: pt_twentythird_question, text: "Distraído", answer_type: "red")
pt_q23_answer_2 = Answer.create(question: pt_twentythird_question, text: "Aferrado", answer_type: "yellow")
pt_q23_answer_3 = Answer.create(question: pt_twentythird_question, text: "Resentido", answer_type: "green")
pt_q23_answer_4 = Answer.create(question: pt_twentythird_question, text: "Temeroso", answer_type: "blue")

pt_twentyfourth_question = Question.create(test: personality_test, text: "")
pt_q24_answer_1 = Answer.create(question: pt_twentyfourth_question, text: "Olvidadizo", answer_type: "red")
pt_q24_answer_2 = Answer.create(question: pt_twentyfourth_question, text: "Brusco", answer_type: "yellow")
pt_q24_answer_3 = Answer.create(question: pt_twentyfourth_question, text: "Antisocial", answer_type: "green")
pt_q24_answer_4 = Answer.create(question: pt_twentyfourth_question, text: "Sumiso", answer_type: "blue")

pt_twentyfifth_question = Question.create(test: personality_test, text: "")
pt_q25_answer_1 = Answer.create(question: pt_twentyfifth_question, text: "Exagerado", answer_type: "red")
pt_q25_answer_2 = Answer.create(question: pt_twentyfifth_question, text: "Impaciente", answer_type: "yellow")
pt_q25_answer_3 = Answer.create(question: pt_twentyfifth_question, text: "Inexpresivo", answer_type: "green")
pt_q25_answer_4 = Answer.create(question: pt_twentyfifth_question, text: "Cedes", answer_type: "blue")

pt_twentysixth_question = Question.create(test: personality_test, text: "")
pt_q26_answer_1 = Answer.create(question: pt_twentysixth_question, text: "Atrabancado", answer_type: "red")
pt_q26_answer_2 = Answer.create(question: pt_twentysixth_question, text: "Intrusivo", answer_type: "yellow")
pt_q26_answer_3 = Answer.create(question: pt_twentysixth_question, text: "Posesivo", answer_type: "green")
pt_q26_answer_4 = Answer.create(question: pt_twentysixth_question, text: "Sacrificado", answer_type: "blue")

pt_twentyseventh_question = Question.create(test: personality_test, text: "")
pt_q27_answer_1 = Answer.create(question: pt_twentyseventh_question, text: "Promotor", answer_type: "red")
pt_q27_answer_2 = Answer.create(question: pt_twentyseventh_question, text: "Positivo", answer_type: "yellow")
pt_q27_answer_3 = Answer.create(question: pt_twentyseventh_question, text: "Planificador", answer_type: "green")
pt_q27_answer_4 = Answer.create(question: pt_twentyseventh_question, text: "Paciente", answer_type: "blue")

pt_twentyeighth_question = Question.create(test: personality_test, text: "")
pt_q28_answer_1 = Answer.create(question: pt_twentyeighth_question, text: "Dejas a medias", answer_type: "red")
pt_q28_answer_2 = Answer.create(question: pt_twentyeighth_question, text: "Terco", answer_type: "yellow")
pt_q28_answer_3 = Answer.create(question: pt_twentyeighth_question, text: "Duda", answer_type: "green")
pt_q28_answer_4 = Answer.create(question: pt_twentyeighth_question, text: "Miedoso", answer_type: "blue")

pt_twentyninth_question = Question.create(test: personality_test, text: "")
pt_q29_answer_1 = Answer.create(question: pt_twentyninth_question, text: "Distraído", answer_type: "red")
pt_q29_answer_2 = Answer.create(question: pt_twentyninth_question, text: "Orgulloso", answer_type: "yellow")
pt_q29_answer_3 = Answer.create(question: pt_twentyninth_question, text: "Pesimista", answer_type: "green")
pt_q29_answer_4 = Answer.create(question: pt_twentyninth_question, text: "Permisivo", answer_type: "blue")

pt_thirtieth_question = Question.create(test: personality_test, text: "")
pt_q30_answer_1 = Answer.create(question: pt_thirtieth_question, text: "Berrinchudo", answer_type: "red")
pt_q30_answer_2 = Answer.create(question: pt_thirtieth_question, text: "Iracundo", answer_type: "yellow")
pt_q30_answer_3 = Answer.create(question: pt_thirtieth_question, text: "Hiriente", answer_type: "green")
pt_q30_answer_4 = Answer.create(question: pt_thirtieth_question, text: "Vas con la corriente", answer_type: "blue")

pt_thirtyfirst_question = Question.create(test: personality_test, text: "")
pt_q31_answer_1 = Answer.create(question: pt_thirtyfirst_question, text: "Desatento", answer_type: "red")
pt_q31_answer_2 = Answer.create(question: pt_thirtyfirst_question, text: "Necio", answer_type: "yellow")
pt_q31_answer_3 = Answer.create(question: pt_thirtyfirst_question, text: "Negativo", answer_type: "green")
pt_q31_answer_4 = Answer.create(question: pt_thirtyfirst_question, text: "Inocente", answer_type: "blue")

pt_thirtysecond_question = Question.create(test: personality_test, text: "")
pt_q32_answer_1 = Answer.create(question: pt_thirtysecond_question, text: "Buscas reconocimiento", answer_type: "red")
pt_q32_answer_2 = Answer.create(question: pt_thirtysecond_question, text: "Adicto al trabajo", answer_type: "yellow")
pt_q32_answer_3 = Answer.create(question: pt_thirtysecond_question, text: "Calculador", answer_type: "green")
pt_q32_answer_4 = Answer.create(question: pt_thirtysecond_question, text: "Te resistes al  cambio", answer_type: "blue")

pt_thirtythird_question = Question.create(test: personality_test, text: "")
pt_q33_answer_1 = Answer.create(question: pt_thirtythird_question, text: "Parlanchín", answer_type: "red")
pt_q33_answer_2 = Answer.create(question: pt_thirtythird_question, text: "Sin tacto", answer_type: "yellow")
pt_q33_answer_3 = Answer.create(question: pt_thirtythird_question, text: "Depresivo", answer_type: "green")
pt_q33_answer_4 = Answer.create(question: pt_thirtythird_question, text: "Temeroso", answer_type: "blue")

pt_thirtyfourth_question = Question.create(test: personality_test, text: "")
pt_q34_answer_1 = Answer.create(question: pt_thirtyfourth_question, text: "Desorganizado", answer_type: "red")
pt_q34_answer_2 = Answer.create(question: pt_thirtyfourth_question, text: "Dominante", answer_type: "yellow")
pt_q34_answer_3 = Answer.create(question: pt_thirtyfourth_question, text: "Dudoso", answer_type: "green")
pt_q34_answer_4 = Answer.create(question: pt_thirtyfourth_question, text: "Flojo", answer_type: "blue")

pt_thirtyfifth_question = Question.create(test: personality_test, text: "")
pt_q35_answer_1 = Answer.create(question: pt_thirtyfifth_question, text: "Inconsistente", answer_type: "red")
pt_q35_answer_2 = Answer.create(question: pt_thirtyfifth_question, text: "Intolerante", answer_type: "yellow")
pt_q35_answer_3 = Answer.create(question: pt_thirtyfifth_question, text: "Indiferente", answer_type: "green")
pt_q35_answer_4 = Answer.create(question: pt_thirtyfifth_question, text: "Introvertido", answer_type: "blue")

pt_thirtysixth_question = Question.create(test: personality_test, text: "")
pt_q36_answer_1 = Answer.create(question: pt_thirtysixth_question, text: "Desordenado", answer_type: "red")
pt_q36_answer_2 = Answer.create(question: pt_thirtysixth_question, text: "Enojón", answer_type: "yellow")
pt_q36_answer_3 = Answer.create(question: pt_thirtysixth_question, text: "Manipulador", answer_type: "green")
pt_q36_answer_4 = Answer.create(question: pt_thirtysixth_question, text: "Hablas bajo", answer_type: "blue")

pt_thirtyseventh_question = Question.create(test: personality_test, text: "")
pt_q37_answer_1 = Answer.create(question: pt_thirtyseventh_question, text: "Exhibicionista", answer_type: "red")
pt_q37_answer_2 = Answer.create(question: pt_thirtyseventh_question, text: "Obstinado", answer_type: "yellow")
pt_q37_answer_3 = Answer.create(question: pt_thirtyseventh_question, text: "Escéptico", answer_type: "green")
pt_q37_answer_4 = Answer.create(question: pt_thirtyseventh_question, text: "Lento", answer_type: "blue")

pt_thirtyeighth_question = Question.create(test: personality_test, text: "")
pt_q38_answer_1 = Answer.create(question: pt_thirtyeighth_question, text: "Gritón", answer_type: "red")
pt_q38_answer_2 = Answer.create(question: pt_thirtyeighth_question, text: "Autoritario", answer_type: "yellow")
pt_q38_answer_3 = Answer.create(question: pt_thirtyeighth_question, text: "Solitario", answer_type: "green")
pt_q38_answer_4 = Answer.create(question: pt_thirtyeighth_question, text: "Seguidor", answer_type: "blue")

pt_thirtyninth_question = Question.create(test: personality_test, text: "")
pt_q39_answer_1 = Answer.create(question: pt_thirtyninth_question, text: "Impuntual", answer_type: "red")
pt_q39_answer_2 = Answer.create(question: pt_thirtyninth_question, text: "Inflexible", answer_type: "yellow")
pt_q39_answer_3 = Answer.create(question: pt_thirtyninth_question, text: "Vengativo", answer_type: "green")
pt_q39_answer_4 = Answer.create(question: pt_thirtyninth_question, text: "Ermitaño", answer_type: "blue")

pt_fourtieth_question = Question.create(test: personality_test, text: "")
pt_q40_answer_1 = Answer.create(question: pt_fourtieth_question, text: "Voluble", answer_type: "red")
pt_q40_answer_2 = Answer.create(question: pt_fourtieth_question, text: "No sabes perder", answer_type: "yellow")
pt_q40_answer_3 = Answer.create(question: pt_fourtieth_question, text: "Criticón", answer_type: "green")
pt_q40_answer_4 = Answer.create(question: pt_fourtieth_question, text: "Procrastinas", answer_type: "blue")

#Test del módulo 1
test_modulo_1 = Test.create(name: "Módulo uno", test_type: "correct_incorrect", code: "module_1")
tm1_question_1 = Question.create(test: test_modulo_1, text: "¿Cuántos fundadores tiene Xango y de qué industria provienen todos?")
tm1_q1_answer_1 = Answer.create(question: tm1_question_1, text:"Son 5, provienen del mundo financiero", answer_type: "incorrect")
tm1_q1_answer_2 = Answer.create(question: tm1_question_1, text:"Son 6, provienen de otras empresas de redes", answer_type: "correct")
tm1_q1_answer_3 = Answer.create(question: tm1_question_1, text:"Son 4, provienen de empresas de venta directa", answer_type: "incorrect")
tm1_q1_answer_4 = Answer.create(question: tm1_question_1, text:"Son 6, provienen de distintas industrias", answer_type: "incorrect")

tm1_question_2 = Question.create(test: test_modulo_1, text: "¿En qué año arrancó operaciones la empresa?")
tm1_q2_answer_1 = Answer.create(question: tm1_question_2, text:"2000", answer_type: "incorrect")
tm1_q2_answer_2 = Answer.create(question: tm1_question_2, text:"2002", answer_type: "correct")
tm1_q2_answer_3 = Answer.create(question: tm1_question_2, text:"2003", answer_type: "incorrect")
tm1_q2_answer_4 = Answer.create(question: tm1_question_2, text:"2005", answer_type: "incorrect")

tm1_question_3 = Question.create(test: test_modulo_1, text: "¿A cuánto ascienden las ventas acumuladas de Xango?")
tm1_q3_answer_1 = Answer.create(question: tm1_question_3, text:"1000 millones de dólares", answer_type: "incorrect")
tm1_q3_answer_2 = Answer.create(question: tm1_question_3, text:"600 millones de dólares", answer_type: "incorrect")
tm1_q3_answer_3 = Answer.create(question: tm1_question_3, text:"2000 millones de dólares", answer_type: "correct")
tm1_q3_answer_4 = Answer.create(question: tm1_question_3, text:"1200 millones de dólares", answer_type: "incorrect")

tm1_question_4 = Question.create(test: test_modulo_1, text: "¿De cuántas personas es recomendable hacer la lista de prospectos?")
tm1_q4_answer_1 = Answer.create(question: tm1_question_4, text:"de los más posibles", answer_type: "incorrect")
tm1_q4_answer_2 = Answer.create(question: tm1_question_4, text:"de 15", answer_type: "incorrect")
tm1_q4_answer_3 = Answer.create(question: tm1_question_4, text:"de más de 25", answer_type: "correct")
tm1_q4_answer_4 = Answer.create(question: tm1_question_4, text:"de 100 por lo menos", answer_type: "incorrect")

tm1_question_5 = Question.create(test: test_modulo_1, text: "¿De dónde debo obtener mi lista de prospectos?")
tm1_q5_answer_1 = Answer.create(question: tm1_question_5, text:"de mi círculo de influencia", answer_type: "correct")
tm1_q5_answer_2 = Answer.create(question: tm1_question_5, text:"de crear una página web", answer_type: "incorrect")
tm1_q5_answer_3 = Answer.create(question: tm1_question_5, text:"mi patrocinador me la dará", answer_type: "incorrect")
tm1_q5_answer_4 = Answer.create(question: tm1_question_5, text:"de poner anuncios en periódicos y bolsas de trabajo", answer_type: "incorrect")

tm1_question_6 = Question.create(test: test_modulo_1, text: "¿Qué debo evitar al llamar a mis prospectos?")
tm1_q6_answer_1 = Answer.create(question: tm1_question_6, text:"resolver todas sus preguntas", answer_type: "incorrect")
tm1_q6_answer_2 = Answer.create(question: tm1_question_6, text:"tener una charla social", answer_type: "incorrect")
tm1_q6_answer_3 = Answer.create(question: tm1_question_6, text:"que se queden intrigados", answer_type: "incorrect")
tm1_q6_answer_4 = Answer.create(question: tm1_question_6, text:"1 y 2", answer_type: "correct")

tm1_question_7 = Question.create(test: test_modulo_1, text: "¿Qué debo hacer al llamar a mis prospectos?")
tm1_q7_answer_1 = Answer.create(question: tm1_question_7, text:"despertar su curiosidad", answer_type: "incorrect")
tm1_q7_answer_2 = Answer.create(question: tm1_question_7, text:"hacerles un elogio sincero", answer_type: "incorrect")
tm1_q7_answer_3 = Answer.create(question: tm1_question_7, text:"decir que tienes prisa", answer_type: "incorrect")
tm1_q7_answer_4 = Answer.create(question: tm1_question_7, text:"todas las anteriores", answer_type: "correct")

tm1_question_8 = Question.create(test: test_modulo_1, text: "¿Cuál es uno de los retos más fuertes que implica este proyecto?")
tm1_q8_answer_1 = Answer.create(question: tm1_question_8, text:"sobrepasar los no", answer_type: "correct")
tm1_q8_answer_2 = Answer.create(question: tm1_question_8, text:"aprender todo sobre la fruta", answer_type: "incorrect")
tm1_q8_answer_3 = Answer.create(question: tm1_question_8, text:"hacer correctamente la lista", answer_type: "incorrect")
tm1_q8_answer_4 = Answer.create(question: tm1_question_8, text:"lograr que la gente se tome el jugo", answer_type: "incorrect")

tm1_question_9 = Question.create(test: test_modulo_1, text: "¿A qué llamamos edificación? ")
tm1_q9_answer_1 = Answer.create(question: tm1_question_9, text:"a construir un negocio sólido", answer_type: "incorrect")
tm1_q9_answer_2 = Answer.create(question: tm1_question_9, text:"a no quejarse", answer_type: "incorrect")
tm1_q9_answer_3 = Answer.create(question: tm1_question_9, text:"a hablar bien de alguien", answer_type: "correct")
tm1_q9_answer_4 = Answer.create(question: tm1_question_9, text:"a tener bien estructurado el grupo", answer_type: "incorrect")

tm1_question_10 = Question.create(test: test_modulo_1, text: "¿Qué herramienta de capacitación me ofrece iuvare?")
tm1_q10_answer_1 = Answer.create(question: tm1_question_10, text:"cursos en el extranjero", answer_type: "incorrect")
tm1_q10_answer_2 = Answer.create(question: tm1_question_10, text:"visitas de líderes a mi casa", answer_type: "incorrect")
tm1_q10_answer_3 = Answer.create(question: tm1_question_10, text:"suscripción a revistas especializadas", answer_type: "incorrect")
tm1_q10_answer_4 = Answer.create(question: tm1_question_10, text:"ninguna de las anteriores", answer_type: "correct")

#Test del módulo 2
test_modulo_2 = Test.create(name: "Módulo dos", test_type: "correct_incorrect", code: "module_2")
tm2_question_1 = Question.create(test: test_modulo_2, text: "¿Cuáles son los 2 parámetros que se deben cuplir para ir calificando en XanGo?")
tm2_q1_answer_1 = Answer.create(question: tm2_question_1, text:"Entusiasmo y volumen", answer_type: "incorrect")
tm2_q1_answer_2 = Answer.create(question: tm2_question_1, text:"Estructura y volumen", answer_type: "correct")
tm2_q1_answer_3 = Answer.create(question: tm2_question_1, text:"Sólo estructura", answer_type: "incorrect")
tm2_q1_answer_4 = Answer.create(question: tm2_question_1, text:"Sólo volumen", answer_type: "incorrect")

tm2_question_2 = Question.create(test: test_modulo_2, text: "¿Cómo funciona el patrocinio y la colocación en tu organización?")
tm2_q2_answer_1 = Answer.create(question: tm2_question_2, text:"Patrocinio te da calificación y colocación volumen", answer_type: "correct")
tm2_q2_answer_2 = Answer.create(question: tm2_question_2, text:"Patrocinio son los puntos de mi volumen de grupo", answer_type: "incorrect")
tm2_q2_answer_3 = Answer.create(question: tm2_question_2, text:"Patrocinio te da volumen y colocación te da calificación", answer_type: "incorrect")
tm2_q2_answer_4 = Answer.create(question: tm2_question_2, text:"Ninguna de las anteriores", answer_type: "incorrect")

tm2_question_3 = Question.create(test: test_modulo_2, text: "¿En iuvare cómo es que garantizas que siempre vas a cobrar del socio clave?")
tm2_q3_answer_1 = Answer.create(question: tm2_question_3, text:"Porque sólo regalo mi consumo personal a mi upline", answer_type: "incorrect")
tm2_q3_answer_2 = Answer.create(question: tm2_question_3, text:"Porque regalo el patrocinio y la colocación a mi upline", answer_type: "incorrect")
tm2_q3_answer_3 = Answer.create(question: tm2_question_3, text:"Porque sólo regalo el patrocinio a mi upline y yo mantengo la colocación", answer_type: "correct")
tm2_q3_answer_4 = Answer.create(question: tm2_question_3, text:"Por todas las anteriores", answer_type: "incorrect")

tm2_question_4 = Question.create(test: test_modulo_2, text: "¿Cuáles son los requisitos mínimos para calificar como 1K?")
tm2_q4_answer_1 = Answer.create(question: tm2_question_4, text:"Ocho frontales y un volumen de grupo de 8 cajas", answer_type: "incorrect")
tm2_q4_answer_2 = Answer.create(question: tm2_question_4, text:"Dos frontales y un volumen 12 cajas", answer_type: "incorrect")
tm2_q4_answer_3 = Answer.create(question: tm2_question_4, text:"Tres frontales y un volumen de 10 cajas", answer_type: "correct")
tm2_q4_answer_4 = Answer.create(question: tm2_question_4, text:"Únicamente con un volumen personal de 10 cajas", answer_type: "incorrect")

tm2_question_5 = Question.create(test: test_modulo_2, text: "¿Cuáles son los requisitos para calificar como Premier 50K?")
tm2_q5_answer_1 = Answer.create(question: tm2_question_5, text:"Mínimo 3 patrocinados directos como 20K y uno como 5K y un volumen de 1000 cajas", answer_type: "incorrect")
tm2_q5_answer_2 = Answer.create(question: tm2_question_5, text:"Mínimo 2 patrocinados directos como Premier 200K y dos como 5K y un volumen de 500 cajas", answer_type: "incorrect")
tm2_q5_answer_3 = Answer.create(question: tm2_question_5, text:"Mínimo 2 patrocinados directos como 20K y dos como 5K y un volumen de 5000 puntos", answer_type: "incorrect")
tm2_q5_answer_4 = Answer.create(question: tm2_question_5, text:"Mínimo 2 patrocinados directos como 20K y uno como 5K y un volumen de 500 cajas", answer_type: "correct")

tm2_question_6 = Question.create(test: test_modulo_2, text: "¿Qué porcentaje reparte XanGo del consumo de cada producto entre sus distribuidores?")
tm2_q6_answer_1 = Answer.create(question: tm2_question_6, text:"50%", answer_type: "correct")
tm2_q6_answer_2 = Answer.create(question: tm2_question_6, text:"Al infinito", answer_type: "incorrect")
tm2_q6_answer_3 = Answer.create(question: tm2_question_6, text:"7%", answer_type: "incorrect")
tm2_q6_answer_4 = Answer.create(question: tm2_question_6, text:"15%", answer_type: "incorrect")

tm2_question_7 = Question.create(test: test_modulo_2, text: "¿Cuántos niveles paga XanGo en comisiones?")
tm2_q7_answer_1 = Answer.create(question: tm2_question_7, text:"1 nivel", answer_type: "incorrect")
tm2_q7_answer_2 = Answer.create(question: tm2_question_7, text:"9 niveles", answer_type: "correct")
tm2_q7_answer_3 = Answer.create(question: tm2_question_7, text:"3 niveles", answer_type: "incorrect")
tm2_q7_answer_4 = Answer.create(question: tm2_question_7, text:"2 niveles", answer_type: "incorrect")

tm2_question_8 = Question.create(test: test_modulo_2, text: "¿Cuál es el porcentaje que paga XanGo en un tercer nivel?")
tm2_q8_answer_1 = Answer.create(question: tm2_question_8, text:"5%", answer_type: "incorrect")
tm2_q8_answer_2 = Answer.create(question: tm2_question_8, text:"6%", answer_type: "incorrect")
tm2_q8_answer_3 = Answer.create(question: tm2_question_8, text:"8%", answer_type: "incorrect")
tm2_q8_answer_4 = Answer.create(question: tm2_question_8, text:"10%", answer_type: "correct")

tm2_question_9 = Question.create(test: test_modulo_2, text: "¿Cuánto te pagan por power start de tus frontales?")
tm2_q9_answer_1 = Answer.create(question: tm2_question_9, text:"30%", answer_type: "correct")
tm2_q9_answer_2 = Answer.create(question: tm2_question_9, text:"50%", answer_type: "incorrect")
tm2_q9_answer_3 = Answer.create(question: tm2_question_9, text:"Nada", answer_type: "incorrect")
tm2_q9_answer_4 = Answer.create(question: tm2_question_9, text:"100%", answer_type: "incorrect")

tm2_question_10 = Question.create(test: test_modulo_2, text: "¿Cuánto reparte XanGo en donaciones?")
tm2_q10_answer_1 = Answer.create(question: tm2_question_10, text:"Todo", answer_type: "incorrect")
tm2_q10_answer_2 = Answer.create(question: tm2_question_10, text:"Nada", answer_type: "incorrect")
tm2_q10_answer_3 = Answer.create(question: tm2_question_10, text:"7%", answer_type: "correct")
tm2_q10_answer_4 = Answer.create(question: tm2_question_10, text:"18%", answer_type: "incorrect")

#Test del módulo 3
test_modulo_3 = Test.create(name: "Módulo tres", test_type: "correct_incorrect", code: "module_3")
tm3_question_1 = Question.create(test: test_modulo_3, text: "¿Cuál es el nombre científico del mangostán?")
tm3_q1_answer_1 = Answer.create(question: tm3_question_1, text:"Mangostana Garcinia", answer_type: "incorrect")
tm3_q1_answer_2 = Answer.create(question: tm3_question_1, text:"Garcinia Mangostana", answer_type: "correct")
tm3_q1_answer_3 = Answer.create(question: tm3_question_1, text:"Laurentis Garcín", answer_type: "incorrect")

tm3_question_2 = Question.create(test: test_modulo_3, text: "¿Cuál de estas frutas no se utiliza en el jugo Xango?")
tm3_q2_answer_1 = Answer.create(question: tm3_question_2, text:"Pera", answer_type: "incorrect")
tm3_q2_answer_2 = Answer.create(question: tm3_question_2, text:"Manzana", answer_type: "incorrect")
tm3_q2_answer_3 = Answer.create(question: tm3_question_2, text:"Ciruela", answer_type: "correct")

tm3_question_3 = Question.create(test: test_modulo_3, text: "La empresa con la que Xango se asoció para producir el jugo se llama:")
tm3_q3_answer_1 = Answer.create(question: tm3_question_3, text:"Flavors International", answer_type: "incorrect")
tm3_q3_answer_2 = Answer.create(question: tm3_question_3, text:"Wild Flavors", answer_type: "correct")
tm3_q3_answer_3 = Answer.create(question: tm3_question_3, text:"Thailand Flavors", answer_type: "incorrect")

tm3_question_4 = Question.create(test: test_modulo_3, text: "La proteína C reactiva es un indicador de")
tm3_q4_answer_1 = Answer.create(question: tm3_question_4, text:"Inflamación", answer_type: "correct")
tm3_q4_answer_2 = Answer.create(question: tm3_question_4, text:"Toxicidad", answer_type: "incorrect")
tm3_q4_answer_3 = Answer.create(question: tm3_question_4, text:"Oxidación", answer_type: "incorrect")

tm3_question_5 = Question.create(test: test_modulo_3, text: "¿Qué quiere decir pansistémico?")
tm3_q5_answer_1 = Answer.create(question: tm3_question_5, text:"Que funciona específicamente en un sistema", answer_type: "incorrect")
tm3_q5_answer_2 = Answer.create(question: tm3_question_5, text:"Que no funciona en ningún sistema", answer_type: "incorrect")
tm3_q5_answer_3 = Answer.create(question: tm3_question_5, text:"Que funciona en diferentes sistemas", answer_type: "correct")

tm3_question_6 = Question.create(test: test_modulo_3, text: "El jugo Xango ¿contiene estilbenos?")
tm3_q6_answer_1 = Answer.create(question: tm3_question_6, text:"Si", answer_type: "correct")
tm3_q6_answer_2 = Answer.create(question: tm3_question_6, text:"No", answer_type: "incorrect")

tm3_question_7 = Question.create(test: test_modulo_3, text: "El jugo Xango ¿contiene Omega 3?")
tm3_q7_answer_1 = Answer.create(question: tm3_question_7, text:"Si", answer_type: "incorrect")
tm3_q7_answer_2 = Answer.create(question: tm3_question_7, text:"No", answer_type: "correct")

tm3_question_8 = Question.create(test: test_modulo_3, text: "La dosis mínima sugerida de jugo Xango es de")
tm3_q8_answer_1 = Answer.create(question: tm3_question_8, text:"3 onzas diarias", answer_type: "incorrect")
tm3_q8_answer_2 = Answer.create(question: tm3_question_8, text:"2 onzas diarias", answer_type: "correct")
tm3_q8_answer_3 = Answer.create(question: tm3_question_8, text:"1 onza diaria", answer_type: "incorrect")

tm3_question_9 = Question.create(test: test_modulo_3, text: "El jugo Xango ¿lo pueden tomar personas con Púrpura?")
tm3_q9_answer_1 = Answer.create(question: tm3_question_9, text:"Si", answer_type: "correct")
tm3_q9_answer_2 = Answer.create(question: tm3_question_9, text:"No", answer_type: "incorrect")

tm3_question_10 = Question.create(test: test_modulo_3, text: "¿Qué porcentaje de las personas que toman el jugo Xango presentan crisis curativa?")
tm3_q10_answer_1 = Answer.create(question: tm3_question_10, text:"1%", answer_type: "correct")
tm3_q10_answer_2 = Answer.create(question: tm3_question_10, text:"5%", answer_type: "incorrect")
tm3_q10_answer_3 = Answer.create(question: tm3_question_10, text:"7%", answer_type: "incorrect")

#Test del taller de arranque
test_basics = Test.create(name: "Taller de arranque", test_type: "correct_incorrect", code: "basics")
tb_question_1 = Question.create(test: test_basics, text: "¿Qué determina el tamaño de tu contexto (árbol)?")
tb_q1_answer_1 = Answer.create(question: tb_question_1, text:"tus metas y deseos", answer_type: "incorrect")
tb_q1_answer_2 = Answer.create(question: tb_question_1, text:"el tamaño de tus sueños y la espectativa que tengas", answer_type: "correct")
tb_q1_answer_3 = Answer.create(question: tb_question_1, text:"las habilidades interpersonales que generas", answer_type: "incorrect")
tb_q1_answer_4 = Answer.create(question: tb_question_1, text:"cursos de desarrollo personal", answer_type: "incorrect")

tb_question_2 = Question.create(test: test_basics, text: "¿Cómo puedo alimentar mi contexto?")
tb_q2_answer_1 = Answer.create(question: tb_question_2, text:"Yendo a cursos de desarrollo personal cada mes para aprender nuevas habilidades", answer_type: "incorrect")
tb_q2_answer_2 = Answer.create(question: tb_question_2, text:"Con un coach personal que me ayude a estirarme y a subir mi propio estándar", answer_type: "incorrect")
tb_q2_answer_3 = Answer.create(question: tb_question_2, text:"alimentando mi certeza rodeándote de la gente correcta, escuchando cds, libros, seminarios y convenciones", answer_type: "correct")
tb_q2_answer_4 = Answer.create(question: tb_question_2, text:"Yendo diario al plan", answer_type: "incorrect")

tb_question_3 = Question.create(test: test_basics, text: "¿Cuál es la piedra angular de nuestro negocio?")
tb_q3_answer_1 = Answer.create(question: tb_question_3, text:"La certeza", answer_type: "correct")
tb_q3_answer_2 = Answer.create(question: tb_question_3, text:"el Jugo", answer_type: "incorrect")
tb_q3_answer_3 = Answer.create(question: tb_question_3, text:"el plan de compensacion", answer_type: "incorrect")
tb_q3_answer_4 = Answer.create(question: tb_question_3, text:"el mangostán", answer_type: "incorrect")

tb_question_4 = Question.create(test: test_basics, text: "¿Quién es responsable de lo que pasa en tu negocio?")
tb_q4_answer_1 = Answer.create(question: tb_question_4, text:"Yo", answer_type: "correct")
tb_q4_answer_2 = Answer.create(question: tb_question_4, text:"mi upline", answer_type: "incorrect")
tb_q4_answer_3 = Answer.create(question: tb_question_4, text:"mis downlines", answer_type: "incorrect")
tb_q4_answer_4 = Answer.create(question: tb_question_4, text:"los premiers de Iuvare", answer_type: "incorrect")

tb_question_5 = Question.create(test: test_basics, text: "¿Cuál de las siguientes actividades no es un punto medular para poder trabajar efectivamente?")
tb_q5_answer_1 = Answer.create(question: tb_question_5, text:"Agendar tiempo especifico para mi negocio", answer_type: "incorrect")
tb_q5_answer_2 = Answer.create(question: tb_question_5, text:"Hacer una lista de todo mundo", answer_type: "incorrect")
tb_q5_answer_3 = Answer.create(question: tb_question_5, text:"Hacer mi Collage", answer_type: "correct")
tb_q5_answer_4 = Answer.create(question: tb_question_5, text:"Ir al plan", answer_type: "incorrect")

tb_question_6 = Question.create(test: test_basics, text: "¿Cuál de estos no es un paso para la duplicación?")
tb_q6_answer_1 = Answer.create(question: tb_question_6, text:"Yo hago tu observas", answer_type: "incorrect")
tb_q6_answer_2 = Answer.create(question: tb_question_6, text:"Tu lo haces y yo observo", answer_type: "incorrect")
tb_q6_answer_3 = Answer.create(question: tb_question_6, text:"Lo hacemos juntos", answer_type: "incorrect")
tb_q6_answer_4 = Answer.create(question: tb_question_6, text:"Nos juntamos para hacer todo en equipo", answer_type: "correct")

tb_question_7 = Question.create(test: test_basics, text: "¿Cuál de los siguientes no es un tipo de  invitación?")
tb_q7_answer_1 = Answer.create(question: tb_question_7, text:"Invitación directa", answer_type: "incorrect")
tb_q7_answer_2 = Answer.create(question: tb_question_7, text:"Invitación en persona", answer_type: "correct")
tb_q7_answer_3 = Answer.create(question: tb_question_7, text:"Invitación de expansión de negocios", answer_type: "incorrect")
tb_q7_answer_4 = Answer.create(question: tb_question_7, text:"invitación indirecta", answer_type: "incorrect")

tb_question_8 = Question.create(test: test_basics, text: "¿A la hora de hacer una invitacion mi trabajo es?")
tb_q8_answer_1 = Answer.create(question: tb_question_8, text:"Convencer a las personas que tienen que ver lo que estoy haciendo", answer_type: "incorrect")
tb_q8_answer_2 = Answer.create(question: tb_question_8, text:"Traerlos a rastras para que vean el plan", answer_type: "incorrect")
tb_q8_answer_3 = Answer.create(question: tb_question_8, text:"Ponerle la postura de que quizás si califican los van a escoger", answer_type: "correct")

tb_question_9 = Question.create(test: test_basics, text: "¿Qué debes de hacer cuando alguien de cancela una cita?")
tb_q9_answer_1 = Answer.create(question: tb_question_9, text:"Dales las gracias por su tiempo", answer_type: "incorrect")
tb_q9_answer_2 = Answer.create(question: tb_question_9, text:"Reagenda en ese momento", answer_type: "correct")
tb_q9_answer_3 = Answer.create(question: tb_question_9, text:"Queda en llamarles despues para reagendar en otra ocasión", answer_type: "incorrect")
tb_q9_answer_4 = Answer.create(question: tb_question_9, text:"Regáñalos por no haber cumplido su palabra", answer_type: "incorrect")

tb_question_10 = Question.create(test: test_basics, text: "¿Durante el preplán nuestro trabajo es?")
tb_q10_answer_1 = Answer.create(question: tb_question_10, text:"Convencer y hacer que tengan ganas de ver el negocio", answer_type: "incorrect")
tb_q10_answer_2 = Answer.create(question: tb_question_10, text:"Crear expectativa, y motivar a nuestros downlines", answer_type: "incorrect")
tb_q10_answer_3 = Answer.create(question: tb_question_10, text:"Filtrar edificar, y crear expectativa", answer_type: "correct")
tb_q10_answer_4 = Answer.create(question: tb_question_10, text:"Otra", answer_type: "incorrect")

tb_question_11 = Question.create(test: test_basics, text: "¿Qué es lo mas importante que tienes que saber para tener éxito?")
tb_q11_answer_1 = Answer.create(question: tb_question_11, text:"Conocer perfectamente el plan de negocios", answer_type: "incorrect")
tb_q11_answer_2 = Answer.create(question: tb_question_11, text:"Conocer perfectamente el jugo", answer_type: "incorrect")
tb_q11_answer_3 = Answer.create(question: tb_question_11, text:"Conocer al prospecto", answer_type: "correct")

tb_question_12 = Question.create(test: test_basics, text: "A la hora del cierre")
tb_q12_answer_1 = Answer.create(question: tb_question_12, text:"La clave es darle información al prospecto", answer_type: "incorrect")
tb_q12_answer_2 = Answer.create(question: tb_question_12, text:"Explicarle perfectamente el plan de compensación", answer_type: "incorrect")
tb_q12_answer_3 = Answer.create(question: tb_question_12, text:"Hacer preguntas y escuchar y de preferencia dejar que mi upline me ayude", answer_type: "correct")
tb_q12_answer_4 = Answer.create(question: tb_question_12, text:"Ninguna de las anteriores", answer_type: "incorrect")

#Test despues del plan
test_plan = Test.create(name: "Plan", test_type: "multiple", code: "plan")
tb_question_1 = Question.create(test: test_plan, text: "En una escala del 1 al 10, ¿qué nivel de interés despertó en ti la propuesta? (Siendo 1 ningún interés y 10 un gran interés)")
tp_q1_answer_1 = Answer.create(question: tb_question_1, text:"1")
tp_q1_answer_2 = Answer.create(question: tb_question_1, text:"2")
tp_q1_answer_3 = Answer.create(question: tb_question_1, text:"3")
tp_q1_answer_4 = Answer.create(question: tb_question_1, text:"4")
tp_q1_answer_5 = Answer.create(question: tb_question_1, text:"5")
tp_q1_answer_6 = Answer.create(question: tb_question_1, text:"6")
tp_q1_answer_7 = Answer.create(question: tb_question_1, text:"7")
tp_q1_answer_8 = Answer.create(question: tb_question_1, text:"8")
tp_q1_answer_9 = Answer.create(question: tb_question_1, text:"9")
tp_q1_answer_10 = Answer.create(question: tb_question_1, text:"10")

tp_question_2 = Question.create(test: test_plan, text: "¿En qué momento te gustaría que me ponga en contacto contigo?")
tp_q2_answer_1 = Answer.create(question: tp_question_2, text:"Hoy")
tp_q2_answer_2 = Answer.create(question: tp_question_2, text:"Mañana")
tp_q2_answer_3 = Answer.create(question: tp_question_2, text:"No es necesario")

#Assets
# Convencion de nombres [asset_type]_[author]_[title]
# ASSET_TYPES = ['audio', 'seminar', 'convention', 'training', 'document', 'plan']
#asset_type = audio

asset_0 = Asset.create(title: "El enfoque", description: " ", author: "Alexis Budd", source: "audio_Alexis_Budd_El_enfoque.mp3", asset_type: "audio")
asset_1 = Asset.create(title: "Atrévete cambia", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Atrevete_cambia.mp3", asset_type: "audio")
asset_2 = Asset.create(title: "Libertad financiera", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Libertad_financiera.mp3", asset_type: "audio")
asset_3 = Asset.create(title: "Simplifica tu negocio", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Simplifica_tu_negocio.mp3", asset_type: "audio")
#asset_4 = Asset.create(title: "El secreto del millon de dolares", description: " ", author: "David Butler", source: "audio_David_Butler_El_secreto_del_millon_de_dolares.mp3", asset_type: "audio")
asset_5 = Asset.create(title: "Seminario 18 de junio 2011", description: " ", author: "Dr Pepe Cruz", source: "audio_Dr_Pepe_Cruz_Seminario_18_de_junio_2011.mp3", asset_type: "audio")
asset_6 = Asset.create(title: "Excusas y creencias", description: " ", author: "Enrique Flores", source: "audio_Enrique_Flores_Excusas_y_creencias.mp3", asset_type: "audio")
asset_7 = Asset.create(title: "Básicos 1", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Basicos 1.mp3", asset_type: "audio")
asset_8 = Asset.create(title: "Básicos 2", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Basicos 2.mp3", asset_type: "audio")
asset_9 = Asset.create(title: "Buscando el colorín", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Buscando_el_colorin.mp3", asset_type: "audio")
asset_10 = Asset.create(title: "Las reglas del juego", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Las_reglas_del_juego.mp3", asset_type: "audio")
asset_11 = Asset.create(title: "Placer y dolor", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Placer_y_dolor.mp3", asset_type: "audio")
asset_12 = Asset.create(title: "¿Por qué un collage?", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Por_que_un_collage.mp3", asset_type: "audio")
asset_13 = Asset.create(title: "Sé el dueño de tu vida", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Se_el_dueno_de_tu_vida.mp3", asset_type: "audio")
asset_13_1 = Asset.create(title: "Como prospectar", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Como_prospectar.mp3", asset_type: "audio")
asset_13_2 = Asset.create(title: "Proceso de cierre", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Proceso_de_cierre.mp3", asset_type: "audio")

#asset_14 = Asset.create(title: "El cierre 1", description: " ", author: "Iuvare", source: "audio_Iuvare_El_cierre_1.mp3", asset_type: "audio")
#asset_15 = Asset.create(title: "El cierre 2", description: " ", author: "Iuvare", source: "audio_Iuvare_El_cierre_2.mp3", asset_type: "audio")
#asset_16 = Asset.create(title: "El cierre 3", description: " ", author: "Iuvare", source: "audio_Iuvare_El_cierre_3.mp3", asset_type: "audio")
asset_17 = Asset.create(title: "Administración del tiempo", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Administracion_del_tiempo.mp3", asset_type: "audio")
asset_18 = Asset.create(title: "El crossline", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_El_crossline.mp3", asset_type: "audio")
asset_19 = Asset.create(title: "Eres extra o protagonista", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Eres_extra_o_protagonista.mp3", asset_type: "audio")
asset_20 = Asset.create(title: "Libros indispensables", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Libros_indispensables.mp3", asset_type: "audio")
asset_21 = Asset.create(title: "Una magnífica opción ante la crisis", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Una_magnifica_opcion_ante_la_crisis.mp3", asset_type: "audio")
asset_22 = Asset.create(title: "La importancia de tener un sueño", description: " ", author: "Liz Salinas", source: "audio_Liz_Salinas_La_importancia_de_tener_un_sueno.mp3", asset_type: "audio")
asset_23 = Asset.create(title: "Toma acción", description: " ", author: "Marcela Flores", source: "audio_Marcela_Flores_Toma_accion.mp3", asset_type: "audio")
#asset_24 = Asset.create(title: "El cierre", description: " ", author: "Marco Galbiati", source: "audio_Marco_Galbiati_El_cierre.mp3", asset_type: "audio")
#asset_25 = Asset.create(title: "La lista del miedo", description: " ", author: "Marco Galbiati", source: "audio_Marco_Galbiati_La_lista_del_miedo.mp3", asset_type: "audio")
asset_26 = Asset.create(title: "La edificación", description: " ", author: "Marisa Dodero", source: "audio_Marisa_Dodero_La_edificacion.mp3", asset_type: "audio")
asset_27 = Asset.create(title: "Liderazgo", description: " ", author: "Raul Villegas", source: "audio_Raul_Villegas_Liderazgo.mp3", asset_type: "audio")
#asset_28 = Asset.create(title: "Como generar riqueza", description: " ", author: "Raul y Rocio Galindo", source: "audio_Raul_y_Rocio_Galindo_Como_generar_riqueza.mp3", asset_type: "audio")

#asset_type = document

asset_29 = Asset.create(title: "Contrato de distribuidor", description: "Formato que necesitas enviar a XanGo para registrar un nuevo socio", author: "Xango", source: "document_Xango_Contrato_de_distribuidor.pdf", asset_type: "document")
asset_30 = Asset.create(title: "Hoja de Cambio de Patrocinio/Colocación", description: "Con este formato puedes hacer cambios en el patrocinio y/o colocación de tus socios", author: "Xango", source: "document_Xango_Solicitud_de_cambio_de_patrocinio.pdf", asset_type: "document")
#asset_31 = Asset.create(title: "Aaron Garrity ceo of the year", description: "Imagen de la revista Utah Business Magazine", author: "Xango", source: "document_Xango_Aaron_Garrity_ceo_of_the_year.pdf", asset_type: "document")
#asset_32 = Asset.create(title: "Patente Xango", description: "Documento donde podrás leer sobre la patente de Xango", author: "Xango", source: "document_Xango_Patente_Xango.pdf", asset_type: "document")

asset_33 = Asset.create(title: "Reglamento Iuvare", description: "Aquí puedes leer más acerca de las reglas de la metodología", author: "Iuvare", source: "document_Iuvare_Reglamento_Iuvare.pdf", asset_type: "document")
asset_34_ = Asset.create(title: "Plan de Compensación", description: "Plan de compensación BOLD", author: "Xango", source: "document_Xango_plan_de_compensacion.pdf", asset_type: "document")
#asset_34 = Asset.create(title: "iBonus", description: "Generales del programa iBonus", author: "Xango", source: "document_Xango_iBonus.pdf", asset_type: "document")
#asset_35 = Asset.create(title: "Comparte y Ahorra", description: "Generales del Programa", author: "Xango", source: "document_Xango_Comparte_y_ahorra.pdf", asset_type: "document")
asset_36 = Asset.create(title: "Edificar Promover", description: "Presentación utilizada en la 1a. Convención IUVARE 2011", author: "Marisa Dodero", source: "document_Marisa_Dodero_Edificar_Promover.pdf", asset_type: "document")
#asset_37 = Asset.create(title: "Customer connect FAQ", description: "Generales del programa", author: "Xango", source: "document_Xango_Customer_conect_FAQ.pdf", asset_type: "document")
asset_38 = Asset.create(title: "Organización de tiempo", description: "Presentación de Jorge Arzamendi en la 1a. Convención IUVARE 2011", author: "Jorge Arzamendi", source: "document_Jorge_Arzamendi_Organizacion_del_tiempo.pdf", asset_type: "document")
asset_39 = Asset.create(title: "Libertad Financiera", description: "Presentación de Circe Rodríguez en la 1a. Convención IUVARE 2011", author: "Circe Rodríguez", source: "document_Circe_Rodriguez_Libertad_Financiera.pdf", asset_type: "document")
asset_40 = Asset.create(title: "Yo Creador Absoluto", description: "Presentación de Estela Salinas durante el seminario de junio  de 2012", author: "Estela Salinas", source: "document_Estela_Salinas_Yo_creador_absoluto.pdf", asset_type: "document")
asset_41 = Asset.create(title: "Averiguación FORM", description: "Averiguación FORM", author: "Iuvare", source: "document_Iuvare_Averiguacion_FORM.pdf", asset_type: "document")
asset_42 = Asset.create(title: "Seguimiento", description: "Presentación de Jorge Arzamendi en el seminario de agosto de 2011", author: "Jorge Arzamendi", source: "document_Jorge_Arzamendi_Seguimiento.pdf", asset_type: "document")
asset_43 = Asset.create(title: "El sueño", description: "Presentacion de Estela Salinas en el seminario de agosto de 2011", author: "Estela Salinas", source: "document_Estela_Salinas_El_sueno.pdf", asset_type: "document")
#asset_44 = Asset.create(title: "Entrevista Liz Salinas 200k", description: "Entrevista realizada por Xango a nuestra premier 200k Liz Salinas", author: "Xango", source: "document_Xango_Entrevista_a_Liz_Salinas_200k.pdf", asset_type: "document")
#asset_45 = Asset.create(title: "Configurar tu correo en Outlook", description: "Como configurar mi correo electronico con Outlook", author: "Iuvare", source: "document_Iuvare_Configurar_tu_correo_en_Outlook.pdf", asset_type: "document")
#asset_46 = Asset.create(title: "Mi Lista y Enviar el Plan", description: "Como enviar el plan de negocios por correo electronico", author: "Iuvare", source: "document_Iuvare_Enviar_el_plan_por_correo.pdf", asset_type: "document")
asset_47 = Asset.create(title: "Nuestro papel en el México de hoy", description: "Presentación de Jorge Arzamendi durante el seminario del 4 de febrero de 2012", author: "Jorge Arzamendi", source: "document_Jorge_Arzamendi_Nuestro_papel_en_el_mexico_de_hoy.pdf", asset_type: "document")
#asset_48 = Asset.create(title: "Priscilla Harrison", description: "Presentacion de Priscilla Harrison", author: "Iuvare", source: "document_iuvare_Priscilla_Harrison.pdf", asset_type: "document")
asset_47_1 = Asset.create(title: "Brújula", description: "La brújula del Kit", author: "Iuvare", source: "brujula.pdf", asset_type: "document")

#asset_type = training
#asset_49 = Asset.create(title: "Módulo 1", description: "Jorge Arzamendi imparte el Módulo 1", author: "Jorge Arzamendi", source: "training_Jorge_Arzamendi_Modulo_1", asset_type: "training", test_id: test_modulo_1)
#asset_50 = Asset.create(title: "Módulo 2", description: "Circe Rodríguez imparte el Módulo 2", author: "Circe Rodríguez", source: "training_Circe_Rodriguez_Modulo_2", asset_type: "training", test_id: test_modulo_2)
asset_51 = Asset.create(title: "Conferencia de salud", description: "Liz imparte el taller de salud", author: "Liz Salinas", source: "training_Liz_Salinas_Modulo_3", asset_type: "training", test_id: test_modulo_3)

#asset_51_2 = Asset.create(title: "Taller de arranque", description: "Lito imparte el taller de arranque", author: "Israel Galván", source: "training_Lito_Arranque", asset_type: "training")

asset_51_1 = Asset.create(title: "Taller 1 Movimiento - Parte 1", description: "Circe imparte la primera parte", author: "Circe Rodríguez", source: "taller_1_movimiento_iuvare_parte_1_circe", asset_type: "training")
asset_51_2 = Asset.create(title: "Taller 1 Movimiento - Parte 2", description: "Circe imparte la segunda parte", author: "Circe Rodríguez", source: "taller_1_movimiento_iuvare_parte_2_circe", asset_type: "training")
asset_51_3 = Asset.create(title: "Taller 1 Movimiento - Parte 3", description: "Lito imparte la tercera parte", author: "Israel Galván", source: "taller_1_movimiento_segunda_parte_lito", asset_type: "training")

#asset_52 = Asset.create(title: "Modulo 4", description: "Raul Villegas imparte el Modulo 4", author: "Raul Villegas", source: "training_Raul_Villegas_Modulo_4", asset_type: "training", test_id: test_modulo_4)
#asset_53 = Asset.create(title: "Taller Plan de Compensación", description: "Samuel Beutelspacher imparte el taller de Plan de Compensación", author: "Samuel Beutelspacher", source: "training_Samuel_Beutelspacher_Taller_Plan_de_Compensacion", asset_type: "training", test_id: test_basics)
asset_54 = Asset.create(title: "Sesión de respuestas médicas(inglés)", description: "Sesión de respuestas médicas impartida por el Dr. Templeman (Convención IUVARE 2011)(INGLÉS)", author: "Dr Frederic Templeman", source: "training_Dr_Frederic_Templeman_Sesion_de_respuestas_medicas(ingles)", asset_type: "training")
#asset_55 = Asset.create(title: "Glimpse(ingles)", description: "Beverly Hollister Glimpse(ingles)", author: "Beverly Hollister", source: "training_Beverly_Hollister_Glimpse(ingles)", asset_type: "training")/Pea/
asset_58 = Asset.create(title: "Planes de compensación", description: "Estela Salinas explica los diferentes planes de compensación", author: "Estela Salinas", source: "training_Estela_Salinas_Planes_de_compensacion", asset_type: "training")
asset_64 = Asset.create(title: "Reglas de IUVARE", description: "Liz Salinas explica las reglas de IUVARE.", author: "Liz Salinas", source: "training_Liz_Salinas_Reglas_de_iuvare", asset_type: "training")
#asset_65 = Asset.create(title: "La revolucion del bienestar", description: "La revolucion del bienestar", author: "Paul Zane Pilser", source: "training_Paul_Zane_Pilser_La_revolucion_del_bienestar", asset_type: "training")
#asset_66 = Asset.create(title: "Xango presentando a Estela Salinas", description: "Video producido por Xango presentando a Estela Salinas", author: "Estela Salinas", source: "training_Estela_Salinas_Xango_presentando_a_Estela_Salinas", asset_type: "training")
#asset_67 = Asset.create(title: "Capacitacion Priscilla Harrison", description: "Capacitacion Priscilla Harrison", author: "Priscilla Harrison", source: "training_Priscilla_Harrison_Capacitacion_Priscilla_Harrison", asset_type: "training")
#asset_68 = Asset.create(title: "Capacitacion Priscilla Harrison(ingles)", description: "Capacitacion Priscilla Harrison(ingles)", author: "Priscilla Harrison", source: "training_Priscilla_Harrison_Capacitacion_Priscilla_Harrison(ingles)", asset_type: "training")

#asset_type = convention
asset_57 = Asset.create(title: "Discurso de Aaron Garrity", description: "Discurso de Aaron Garrity", author: "Aaron Garrity", source: "convention_Aaron_Garrity_Discurso_de_Aaron_Garrity", asset_type: "convention")
asset_59 = Asset.create(title: "Xango", description: " ", author: "Joe Morton", source: "convention_Joe_Morton_Xango", asset_type: "convention")

asset_69 = Asset.create(title: "Convención Iuvare 2011", description: "El fundador Aaron Garrity en la convención IUVARE 2011", author: "Aaron Garrity", source: "convention_Aaron_Garrity_Convencion_Iuvare_2011", asset_type: "convention")
#asset_70 = Asset.create(title: "Convencion iuvare 2012 pt1", description: "Daniel Hernandez durante la convencion iuvare 2012", author: "Daniel Hernandez", source: "convention_Daniel_Hernandez_Convencion_Iuvare_2012_pt1", asset_type: "convention")
#asset_71 = Asset.create(title: "Convencion iuvare 2012 pt2", description: "Daniel Hernandez cuenta su historia durante la convencion iuvare 2012", author: "Daniel Hernandez", source: "convention_Daniel_Hernandez_Convencion_Iuvare_2012_pt2", asset_type: "convention")
asset_72 = Asset.create(title: "Experiencia con Xango", description: "El Dr Arturo Arenas nos platica su experiencia con Xango", author: "Dr Arturo Arenas", source: "convention_Dr_Arturo_Arenas_Experiencia_con_Xango", asset_type: "convention")
asset_73 = Asset.create(title: "Experiencia con Xango(inglés)", description: "El Dr Frederic Templeman nos platica su experiencia con Xango", author: "Dr Frederic Templeman", source: "convention_Dr_Frederic_Templeman_Experiencia_con_Xango(ingles)", asset_type: "convention")
asset_74 = Asset.create(title: "Convención IUVARE 2011", description: "Gordon Morton durante la convención IUVARE 2011", author: "Gordon Morton", source: "convention_Gordon_Morton_Convencion_Iuvare_2011", asset_type: "convention")
asset_75 = Asset.create(title: "Convención IUVARE 2012", description: "Estela Salinas durante la convención IUVARE 2012", author: "Estela Salinas", source: "convention_Estela_Salinas_Convencion_Iuvare_2012", asset_type: "convention")
asset_76 = Asset.create(title: "Convención IUVARE 2011", description: "Joe Morton durante la convención IUVARE 2011", author: "Joe Morton", source: "convention_Joe_Morton_Convencion_Iuvare_2011", asset_type: "convention")
asset_77 = Asset.create(title: "Convención IUVARE 2012", description: "Joe Morton durante la convención IUVARE 2012", author: "Joe Morton", source: "convention_Joe_Morton_Convencion_Iuvare_2012", asset_type: "convention")
asset_78 = Asset.create(title: "Convención IUVARE 2012", description: "Jorge Arzamendi durante la convención IUVARE 2012", author: "Jorge Arzamendi", source: "convention_Jorge_Arzamendi_Convencion_Iuvare_2012", asset_type: "convention")
asset_79 = Asset.create(title: "Convención IUVARE 2011", description: "Jorge Arzamendi nos enseña la importancia de la correcta administración del tiempo", author: "Jorge Arzamendi", source: "convention_Jorge_Arzamendi_Convencion_Iuvare_2011", asset_type: "convention")
asset_80 = Asset.create(title: "Convención IUVARE 2012", description: "Jorge Font durante la convencion iuvare 2012", author: "Jorge Font", source: "convention_Jorge_Font_Convencion_Iuvare_2012", asset_type: "convention")
asset_81 = Asset.create(title: "Convención IUVARE 2011(inglés)", description: "Kent Wood fundador de Xango nos enseña la importancia de ser diferentes", author: "Kent Wood", source: "convention_Kent_Wood_Convencion_Iuvare_2011(ingles)", asset_type: "convention")
asset_82 = Asset.create(title: "Convención IUVARE 2011", description: "Liz Salinas nos habla sobre el equilibrio en nuestra vida", author: "Liz Salinas", source: "convention_Liz_Salinas_Convencion_Iuvare_2011", asset_type: "convention")
asset_83 = Asset.create(title: "Convención IUVARE 2011", description: "Nuestra Premier 500k Estela Salinas en el cierre de la convención de fin de año IUVARE 2011", author: "Estela Salinas", source: "convention_Estela_Salinas_Convencion_Iuvare_2011", asset_type: "convention")

#asset_type = seminar
asset_62 = Asset.create(title: "Tailandia 2010 día uno", description: "Jorge Arzamendi Tailandia 2010 día uno", author: "Jorge Arzamendi", source: "seminar_Jorge_Arzamendi_Tailandia_2010_dia_uno", asset_type: "seminar")
asset_56 = Asset.create(title: "Tailandia 2010 día dos", description: "Circe Rodríguez Tailandia 2010 día dos", author: "Circe Rodríguez", source: "seminar_Circe_Rodriguez_Tailandia_2010_dia_dos", asset_type: "seminar")
asset_61 = Asset.create(title: "Tailandia 2010 día tres", description: "Raul Villegas Tailandia 2010 día tres", author: "Raul Villegas", source: "seminar_Raul_Villegas_Tailandia_2010_dia_tres", asset_type: "seminar")
asset_60 = Asset.create(title: "Tailandia 2010 día cuatro", description: "Liz Salinas Tailandia 2010 día cuatro", author: "Liz Salinas", source: "seminar_Liz_Salinas_Tailandia_2010_dia_cuatro", asset_type: "seminar")
asset_63 = Asset.create(title: "Tailandia 2010 día cinco", description: "Estela Salinas Tailandia 2010 día cinco", author: "Estela Salinas", source: "seminar_Estela_Salinas_Tailandia_2010_dia_cinco", asset_type: "seminar")

asset_84 = Asset.create(title: "Seminario febrero 2012", description: "Circe Rodríguez Premier 100k nos muestra un método práctico para lograr la libertad financiera ", author: "Circe Rodríguez", source: "seminar_Circe_Rodriguez_Seminario_febrero_2012", asset_type: "seminar")
asset_85 = Asset.create(title: "La cornada al león", description: "Enrique Flores “La cornada al león” Seminario de julio de 2014", author: "Enrique Flores", source: "seminar_Enrique_Flores_La_cornada_al_leon", asset_type: "seminar")
asset_86 = Asset.create(title: "Seminario octubre 2011 pt1", description: "Guillermo Ganem en el seminario IUVARE de octubre de 2011 (Parte 1)", author: "Guillermo Ganem", source: "seminar_Guillermo_Ganem_Seminario_octubre_2011_pt1", asset_type: "seminar")
asset_87 = Asset.create(title: "Seminario octubre 2011 pt2", description: "Guillermo Ganem en el seminario IUVARE de octubre de 2011 (Parte 2)", author: "Guillermo Ganem", source: "seminar_Guillermo_Ganem_Seminario_octubre_2011_pt2", asset_type: "seminar")
asset_88 = Asset.create(title: "Seminario marzo 2013", description: "Estela Salinas durante el seminario de marzo de 2013", author: "Estela Salinas", source: "seminar_Estela_Salinas_Seminario_marzo_2013", asset_type: "seminar")
asset_89 = Asset.create(title: "Seminario post-regional 2010", description: "Joe Morton durante el seminario post-regional 2010", author: "Joe Morton", source: "seminar_Joe_Morton_Seminario_post-regional_2010", asset_type: "seminar")

asset_90 = Asset.create(title: "Seminario marzo 2013", description: "Jorge Arzamendi durante el seminario de marzo de 2013", author: "Jorge Arzamendi", source: "seminar_Jorge_Arzamendi_Seminario_marzo_2013", asset_type: "seminar")
asset_91 = Asset.create(title: "Seminario febrero 2012", description: "Jorge Arzamendi Premier 100k de IUVARE durante el seminario de febrero 2012", author: "Jorge Arzamendi", source: "seminar_Jorge_Arzamendi_Seminario_febrero_2012", asset_type: "seminar")
#asset_92 = Asset.create(title: "La vida como debe ser", description: "Massimo del Moro La vida como debe ser", author: "Massimo del Moro", source: "seminar_Massimo_del_Moro_La_vida_como_debe_ser", asset_type: "seminar")
asset_93 = Asset.create(title: "Seminario mayo 2012", description: "Premier 100k Marisa Dodero durante su seminario en mayo 2012", author: "Marisa Dodero", source: "seminar_Marisa_Dodero_Seminario_mayo_2012", asset_type: "seminar")
asset_94 = Asset.create(title: "Seminario enero 2012 pt1", description: "Primera parte del Seminario de Enrique Flores (8 de enero 2012)", author: "Enrique Flores", source: "seminar_Enrique_Flores_Seminario_enero_2012_pt1", asset_type: "seminar")
asset_95 = Asset.create(title: "El árbol rojo del multinivel pt1", description: "El árbol rojo del multinivel (Parte 1)", author: "Mario Rodríguez Padres", source: "seminar_Mario_Rodriguez_Padres_El_arbol_rojo_del_multinivel_pt1", asset_type: "seminar")
asset_96 = Asset.create(title: "El árbol rojo del multinivel pt2", description: "El árbol rojo del multinivel (Parte 2)", author: "Mario Rodríguez Padres", source: "seminar_Mario_Rodriguez_Padres_El_arbol_rojo_del_multinivel_pt2", asset_type: "seminar")
asset_97 = Asset.create(title: "Yo creador absoluto", description: "Seminario impartido por Estela Salinas en junio de 2012", author: "Estela Salinas", source: "seminar_Estela_Salinas_Yo_creador_absoluto", asset_type: "seminar")
asset_98 = Asset.create(title: "Seminario marzo 2012 pt1", description: "Seminario impartido por Ron White durante el mes de marzo de 2012 (Parte 1)", author: "Ron White", source: "seminar_Ron_White_Seminario_marzo_2012_pt1", asset_type: "seminar")
asset_99 = Asset.create(title: "Seminario marzo 2012 pt2", description: "Seminario impartido por Ron White durante el mes de marzo de 2012 (Parte 2)", author: "Ron White", source: "seminar_Ron_White_Seminario_marzo_2012_pt2", asset_type: "seminar")
#asset_100 = Asset.create(title: "El precio del éxito no es negociable", description: "Liza Cortés El precio del éxito no es negociable", author: "Liza Cortes", source: "seminar_Liza_Cortes_El_precio_del_exito_no_es_negociable", asset_type: "seminar")
asset_101 = Asset.create(title: "AMG", description: "Astrid de Esesarte y Leo Ayala AMG septiembre 2014", author: "Astrid y Leo", source: "seminar_Astrid_y_Leo_AMG", asset_type: "seminar")
asset_102 = Asset.create(title: "Historia", description: "Astrid de Esesarte y Leo Ayala cuentan su historia septiembre 2014", author: "Astrid y Leo", source: "seminar_Astrid_y_Leo_Historia", asset_type: "seminar")
asset_102_01 = Asset.create(title: "La vida es una fiesta", description: "Seminario de Marina Buzali", author: "Marina Buzali", source: "seminar_Marina_Buzali_La_vida_es_una_fiesta", asset_type: "seminar")
asset_102_02 = Asset.create(title: "Hecho en IUVARE", description: "Seminario de Israel Galván", author: "Israel Galván", source: "seminar_Israel_Galvan_Hecho_en_iuvare", asset_type: "seminar")
asset_102_03 = Asset.create(title: "Sé feliz y exitoso", description: "Seminario de Samuel Beutelspacher", author: "Samuel Beutelspacher", source: "seminar_Samuel_Beutelspacher_Se_feliz_y_exitoso", asset_type: "seminar")

asset_103_01 = Asset.create(title: "Seminario de Raúl Villegas", description: "Seminario de Raúl Villegas", author: "Raul Villegas", source: "01_Sem_Raul_Villegas_14", asset_type: "seminar")
asset_103_02 = Asset.create(title: "Seminario de Denisse Ducoing 1a Parte", description: "Seminario de Denisse Ducoing", author: "Denisse Ducoing", source: "02_Sem_Denisse_Ducoing_A", asset_type: "seminar")
asset_103_03 = Asset.create(title: "Seminario de Denisse Ducoing 2a Parte", description: "Seminario de Denisse Ducoing", author: "Denisse Ducoing", source: "03_Sem_Denisse_Ducoing_B", asset_type: "seminar")
asset_103_04 = Asset.create(title: "Seminario de Rodrigo Villegas 1a Parte", description: "Seminario de Rodrigo Villegas", author: "Rodrigo Villegas", source: "04_Sem_Rodrigo_Villegas_A", asset_type: "seminar")
asset_103_05 = Asset.create(title: "Seminario de Rodrigo Villegas 2a Parte", description: "Seminario de Rodrigo Villegas", author: "Rodrigo Villegas", source: "05_Sem_Rodrigo_Villegas_B", asset_type: "seminar")
asset_103_06 = Asset.create(title: "Seminario de Francisco González 1a Parte", description: "Seminario de Francisco González", author: "Francisco González", source: "06_Sem_Francisco_Glez_A", asset_type: "seminar")
asset_103_07 = Asset.create(title: "Seminario de Francisco González 2a Parte", description: "Seminario de Francisco González", author: "Francisco González", source: "07_Sem_Francisco_Glez_B", asset_type: "seminar")
asset_103_08 = Asset.create(title: "Seminario de Liz Salinas 1a Parte", description: "Seminario de Liz Salinas", author: "Liz Salinas", source: "08_Sem_Liz_Salinas_A", asset_type: "seminar")
asset_103_09 = Asset.create(title: "Seminario de Liz Salinas 2a Parte", description: "Seminario de Liz Salinas", author: "Liz Salinas", source: "09_Sem_Liz_Salinas_B", asset_type: "seminar")
asset_103_10 = Asset.create(title: "Seminario de Circe Rodríguez 1a Parte", description: "Seminario de Circe Rodríguez", author: "Circe Rodríguez", source: "10_Sem_Circe_Rd_A", asset_type: "seminar")
asset_103_11 = Asset.create(title: "Seminario de Circe Rodríguez 2a Parte", description: "Seminario de Circe Rodríguez", author: "Circe Rodríguez", source: "11_Sem_Circe_Rdz_B", asset_type: "seminar")
asset_103_12 = Asset.create(title: "Seminario de Circe Rodríguez 3a Parte", description: "Seminario de Circe Rodríguez", author: "Circe Rodríguez", source: "12_Sem_Circe_Rdz_C", asset_type: "seminar")
asset_103_13 = Asset.create(title: "Seminario Post Rush 1a Parte", description: "Seminario Post Rush", author: "Varios", source: "13_Sem_Post_Rush_A", asset_type: "seminar")
asset_103_14 = Asset.create(title: "Seminario Post Rush 2a Parte", description: "Seminario Post Rush", author: "Varios", source: "14_Sem_Post_Rush_B", asset_type: "seminar")
asset_103_15 = Asset.create(title: "Seminario Post Rush 3a Parte", description: "Seminario Post Rush", author: "Varios", source: "15_Sem_Post_Rush_C", asset_type: "seminar")
asset_103_16 = Asset.create(title: "Seminario Samuel y Ana Laura Beutelspacher", description: "Seminario Ciudad de México", author: "Samuel y Ana Laura Beutelspacher", source: "16_Sem_ALM_SB_LS_ES_A", asset_type: "seminar")
asset_103_17 = Asset.create(title: "Seminario Elizabeth y Estela Salinas", description: "Seminario Ciudad de México", author: "Elizabeth y Estela Salinas", source: "17_Sem_ALM_SB_LS_ES_B", asset_type: "seminar")

asset_103_18 = Asset.create(title: "Seminario Javier Vélez", description: "Seminario Javier Vélez", author: "Javier Vélez", source: "18_Sem_Javier_Velez_A", asset_type: "seminar")
asset_103_19 = Asset.create(title: "Seminario Javier Vélez", description: "Seminario Javier Vélez", author: "Javier Vélez", source: "19_Sem_Javier_Velez_B", asset_type: "seminar")


#asset_type = plan
#asset_103 = Asset.create(title: "Plan Jorge Arzamendi", description:"Plan de negocios presentado por Jorge Arzamendi", author:"Jorge Arzamendi", source: "plan_Jorge_Arzamendi_Plan_Jorge_Arzamendi", asset_type: "plan", test_id: test_plan.id)
#asset_104 = Asset.create(title: "Plan Jorge Arzamendi Colombia", description:"Plan de negocios para Colombia presentado por Jorge Arzamendi", author:"Jorge Arzamendi", source: "plan_Jorge_Arzamendi_Plan_Jorge_Arzamendi_Colombia", asset_type: "plan", test_id: test_plan.id)
#asset_105 = Asset.create(title: "Plan Circe Rodríguez", description:"Plan de negocios presentado por Circe Rodríguez", author:"Circe Rodríguez", source: "plan_Circe_Rodriguez_Plan_Circe_Rodriguez", asset_type: "plan", test_id: test_plan.id)
#asset_106 = Asset.create(title: "Plan Circe Rodriguez Colombia", description:"Plan de negocios para Colombia presentado por Circe Rodríguez", author:"Circe Rodríguez", source: "plan_Circe_Rodriguez_Plan_Circe_Rodriguez_Colombia", asset_type: "plan", test_id: test_plan.id)
#asset_107 = Asset.create(title: "Plan Enrique Flores", description:"Plan de negocios presentado por Enrique Flores", author:"Enrique Flores", source: "plan_Enrique_Flores_Plan_Enrique_Flores", asset_type: "plan", test_id: test_plan.id)

asset_106 = Asset.create(title: "Plan Javier Velez", description:"Movimiento Iuvare por Javier Vélez", author:"Javier Vélez", source: "plan_Movimiento_Javier_Velez", asset_type: "plan", test_id: test_plan.id)
asset_107 = Asset.create(title: "Plan Elizabeth Salinas", description:"Movimiento Iuvare por Elizabeth Salinas", author:"Elizabeth Salinas", source: "plan_Movimiento_Liz_Salinas", asset_type: "plan", test_id: test_plan.id)
asset_108_1 = Asset.create(title: "Plan Circe España", description:"Movimiento Iuvare por Circe Rodríguez", author:"Circe Rodríguez", source: "plan_Movimiento_Espana_Circe", asset_type: "plan", test_id: test_plan.id)
asset_108_2 = Asset.create(title: "Plan Jorge Colombia", description:"Movimiento Iuvare por Jorge Arzamendi", author:"Jorge Arzamendi", source: "plan_Movimiento_Jorge_Andres", asset_type: "plan", test_id: test_plan.id)

#asset_type = FAQ
asset_108 = Asset.create(title: "FAQ", description:"Documento PDF del FAQ", author:"FAQ", source: "FAQ.pdf", asset_type: "FAQ")

#Sedes
#sede_1 = Office.create(name: "Morelia", address: "Leon Guzman 78, Col. Centro", latitude: "19.704424", longitude: "-101.196846", description: "", schedule: "Plan: Lunes a viernes 8:00pm")
#sede_2 = Office.create(name: "México - El Ruedo", address: "Augusto Rodin #110 Esq. Maximino Ávila Camacho. Col. Ciudad de los deportes", latitude: "19.3838687", longitude: "-99.1807992", description: "", schedule: "Plan: Lunes a Viernes 6:00pm 8:00pm y Sábado 9:00am")
#sede_3 = Office.create(name: "Guadalajara", address: "Plaza Bonita local sub ancla 1, Av. México 3370, Monraz, CP 44670", latitude: "20.678718", longitude: "-103.402447", description: "", schedule: "Plan: Lunes a Viernes 10:00am, 6:00pm, 8:00pm y Sábado 10:00am")
#sede_4 = Office.create(name: "Toluca", address: "Heriberto Enríquez 361 LT 201 Col. Real de San Javier, Metepec", latitude: "19.262383", longitude: "-99.644541", description: "", schedule: "Plan: Lunes 10:30am, Miércoles 10:00am, Sábado 9:00am, Lunes a Viernes 7:00pm")
#sede_5 = Office.create(name: "Querétaro", address: "Ejército Republicano 139 Int. 104 Col. Carretas", latitude: "20.5892049", longitude: "-100.3731074", description: "", schedule: "Plan: Martes y Jueves 8:00pm, Sábado 10:00am")
#sede_6 = Office.create(name: "México - Big Ben", address: "Cerro de las Campanas No. 3 Torre 1 Piso 6 Edi. Big Ben Col. San Andrés Atenco Tlalnepantla, Edo. de México.", latitude: "19.5413723", longitude: "-99.2148748", description: "", schedule: "Plan: Miércoles 8:00pm")
#sede_7 = Office.create(name: "México - Corporativo", address: "Corporativo Nápoles Av. Insurgentes Sur 863 Piso 1 Col. Nápoles", latitude: "19.3881774", longitude: "-99.1748896", description: "", schedule: "Plan: Martes y Jueves 10:00am")
#sede_8 = Office.create(name: "Tepic", address: "Prisciliano Sánchez 232. Colonia San Antonio", latitude: "21.501437", longitude: "-104.89028", description: "", schedule: "Plan: Lunes a Viernes 8:00pm")
#sede_9 = Office.create(name: "Pto. Vallarta", address: "Milán 327 1er piso Col. La Vena", latitude: "20.6334622", longitude: "-105.2239167", description: "", schedule: "")
#sede_10 = Office.create(name: "León", address: "Blvd. San Pedro 310 Col. San Isidro", latitude: "21.100674", longitude: "-101.6462318", description: "", schedule: "Plan: miércoles 7pm (los demás días con video del plan)")
#sede_11 = Office.create(name: "Puebla", address: "Av. Juárez #1905 4to piso oficina 13 Col. La Paz", latitude: "19.0496801", longitude: "-98.2141658", description: "", schedule: "")
sede_12 = Office.create(name: "MADRID", address: "C/ General Moscardo, 6, 28020", latitude: "40.4472441", longitude: "-3.6990601", description: "", schedule: "Plan: martes y jueves de 8:30pm a 9:30pm")

#Historic Asset

#audios
#ha_audio = HistoricAsset.create(historic_asset_type: "audio", number: "COC33", color: "yellow", author: "Luis Sánchez", name: "Audio Name 01")
#ha_audio_2 = HistoricAsset.create(historic_asset_type: "audio", number: "COC34", color: "red", author: "Ricardo Pérez", name: "Audio Name 02")
#ha_audio_3 = HistoricAsset.create(historic_asset_type: "audio", number: "COC35", color: "purple", author: "Jorge Sánchez", name: "Audio Name 03")

#libros
#ha_book = HistoricAsset.create(historic_asset_type: "book", number: "2014-03-01", author: "Luis Sánchez", name: "Book Name 01")
#ha_book_2 = HistoricAsset.create(historic_asset_type: "book", number: "2014-04-01", author: "Ricardo Pérez", name: "Book Name 02")
#ha_book_3 = HistoricAsset.create(historic_asset_type: "book", number: "2014-05-01", author: "Jorge Sánchez", name: "Book Name 03")
