# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
role_premier = Role.create(name: 'premier')
user = User.create(first_name: "Dios", last_name: "Premier", email: "diospremier@xango.com", xango_id: "123456", iuvare_id: "1234", active: true, xango_rank: "DIOS", password:"xangoxango", roles: [role_premier])
#Invitation.create(user_id: user.id, recipient_email:"correo@correo.com", token:"cualquiercosa")

#Test de Personalidad
personality_test = Test.create(name: "Test de personalidad", test_type: "percentage", code: "color", instructions: "Piensa en las palabras, en lo que significan y no en lo que te gustaría, realmente piensa cual se asemeja más a ti o con cual te sientes más identificado.")

pt_first_question = Question.create(test: personality_test, text: "")
pt_q1_answer_1 = Answer.create(question: pt_first_question, text: "Superficial", answer_type: "red")
pt_q1_answer_2 = Answer.create(question: pt_first_question, text: "Mandón", answer_type: "yellow")
pt_q1_answer_3 = Answer.create(question: pt_first_question, text: "Penoso", answer_type: "green")
pt_q1_answer_4 = Answer.create(question: pt_first_question, text: "Evades", answer_type: "blue")

pt_second_question = Question.create(test: personality_test, text: "")
pt_q2_answer_1 = Answer.create(question: pt_second_question, text: "Indisciplinado", answer_type: "red")
pt_q2_answer_2 = Answer.create(question: pt_second_question, text: "Antipático", answer_type: "yellow")
pt_q2_answer_3 = Answer.create(question: pt_second_question, text: "Rencoroso", answer_type: "green")
pt_q2_answer_4 = Answer.create(question: pt_second_question, text: "Apático", answer_type: "blue")

pt_third_question = Question.create(test: personality_test, text: "")
pt_q3_answer_1 = Answer.create(question: pt_third_question, text: "Aferrado", answer_type: "red")
pt_q3_answer_2 = Answer.create(question: pt_third_question, text: "Desconfiado", answer_type: "yellow")
pt_q3_answer_3 = Answer.create(question: pt_third_question, text: "Resentido", answer_type: "green")
pt_q3_answer_4 = Answer.create(question: pt_third_question, text: "Temeroso", answer_type: "blue")

pt_fourth_question = Question.create(test: personality_test, text: "")
pt_q4_answer_1 = Answer.create(question: pt_fourth_question, text: "Olvidadizo", answer_type: "red")
pt_q4_answer_2 = Answer.create(question: pt_fourth_question, text: "Franco", answer_type: "yellow")
pt_q4_answer_3 = Answer.create(question: pt_fourth_question, text: "Inquieto", answer_type: "green")
pt_q4_answer_4 = Answer.create(question: pt_fourth_question, text: "Miedoso", answer_type: "blue")

pt_fifth_question = Question.create(test: personality_test, text: "")
pt_q5_answer_1 = Answer.create(question: pt_fifth_question, text: "Interrumpe", answer_type: "red")
pt_q5_answer_2 = Answer.create(question: pt_fifth_question, text: "Impaciente", answer_type: "yellow")
pt_q5_answer_3 = Answer.create(question: pt_fifth_question, text: "Inseguro", answer_type: "green")
pt_q5_answer_4 = Answer.create(question: pt_fifth_question, text: "Indeciso", answer_type: "blue")

pt_sixth_question = Question.create(test: personality_test, text: "")
pt_q6_answer_1 = Answer.create(question: pt_sixth_question, text: "Impredecible", answer_type: "red")
pt_q6_answer_2 = Answer.create(question: pt_sixth_question, text: "No afectivo", answer_type: "yellow")
pt_q6_answer_3 = Answer.create(question: pt_sixth_question, text: "No popular", answer_type: "green")
pt_q6_answer_4 = Answer.create(question: pt_sixth_question, text: "No te involucras", answer_type: "blue")

pt_seventh_question = Question.create(test: personality_test, text: "")
pt_q7_answer_1 = Answer.create(question: pt_seventh_question, text: "Dejas a medias", answer_type: "red")
pt_q7_answer_2 = Answer.create(question: pt_seventh_question, text: "Terco", answer_type: "yellow")
pt_q7_answer_3 = Answer.create(question: pt_seventh_question, text: "Difícil de complacer", answer_type: "green")
pt_q7_answer_4 = Answer.create(question: pt_seventh_question, text: "Dudas", answer_type: "blue")

pt_eighth_question = Question.create(test: personality_test, text: "")
pt_q8_answer_1 = Answer.create(question: pt_eighth_question, text: "Permisivo", answer_type: "red")
pt_q8_answer_2 = Answer.create(question: pt_eighth_question, text: "Sientes orgullo de ti", answer_type: "yellow")
pt_q8_answer_3 = Answer.create(question: pt_eighth_question, text: "Pesimista", answer_type: "green")
pt_q8_answer_4 = Answer.create(question: pt_eighth_question, text: "Simple", answer_type: "blue")

pt_ninth_question = Question.create(test: personality_test, text: "")
pt_q9_answer_1 = Answer.create(question: pt_ninth_question, text: "Iracundo", answer_type: "red")
pt_q9_answer_2 = Answer.create(question: pt_ninth_question, text: "Inflexible", answer_type: "yellow")
pt_q9_answer_3 = Answer.create(question: pt_ninth_question, text: "Antagonista", answer_type: "green")
pt_q9_answer_4 = Answer.create(question: pt_ninth_question, text: "Vas con la corriente", answer_type: "blue")

pt_tenth_question = Question.create(test: personality_test, text: "")
pt_q10_answer_1 = Answer.create(question: pt_tenth_question, text: "Inocente", answer_type: "red")
pt_q10_answer_2 = Answer.create(question: pt_tenth_question, text: "Impredecible", answer_type: "yellow")
pt_q10_answer_3 = Answer.create(question: pt_tenth_question, text: "Negativo", answer_type: "green")
pt_q10_answer_4 = Answer.create(question: pt_tenth_question, text: "Indiferente", answer_type: "blue")

pt_eleventh_question = Question.create(test: personality_test, text: "")
pt_q11_answer_1 = Answer.create(question: pt_eleventh_question, text: "Buscas reconocimiento", answer_type: "red")
pt_q11_answer_2 = Answer.create(question: pt_eleventh_question, text: "Adicto al trabajo", answer_type: "yellow")
pt_q11_answer_3 = Answer.create(question: pt_eleventh_question, text: "Afligido", answer_type: "green")
pt_q11_answer_4 = Answer.create(question: pt_eleventh_question, text: "Preocupón", answer_type: "blue")

pt_twelfth_question = Question.create(test: personality_test, text: "")
pt_q12_answer_1 = Answer.create(question: pt_twelfth_question, text: "Parlanchín", answer_type: "red")
pt_q12_answer_2 = Answer.create(question: pt_twelfth_question, text: "Sin tacto", answer_type: "yellow")
pt_q12_answer_3 = Answer.create(question: pt_twelfth_question, text: "Hiper sensible", answer_type: "green")
pt_q12_answer_4 = Answer.create(question: pt_twelfth_question, text: "Temeroso", answer_type: "blue")

pt_thirteenth_question = Question.create(test: personality_test, text: "")
pt_q13_answer_1 = Answer.create(question: pt_thirteenth_question, text: "Desorganizado", answer_type: "red")
pt_q13_answer_2 = Answer.create(question: pt_thirteenth_question, text: "Dominante", answer_type: "yellow")
pt_q13_answer_3 = Answer.create(question: pt_thirteenth_question, text: "Dudoso", answer_type: "green")
pt_q13_answer_4 = Answer.create(question: pt_thirteenth_question, text: "Deprimido", answer_type: "blue")

pt_fourteenth_question = Question.create(test: personality_test, text: "")
pt_q14_answer_1 = Answer.create(question: pt_fourteenth_question, text: "Inconsistente", answer_type: "red")
pt_q14_answer_2 = Answer.create(question: pt_fourteenth_question, text: "Intolerante", answer_type: "yellow")
pt_q14_answer_3 = Answer.create(question: pt_fourteenth_question, text: "Introvertido", answer_type: "green")
pt_q14_answer_4 = Answer.create(question: pt_fourteenth_question, text: "Indiferente", answer_type: "blue")

pt_fifteenth_question = Question.create(test: personality_test, text: "")
pt_q15_answer_1 = Answer.create(question: pt_fifteenth_question, text: "Desordenado", answer_type: "red")
pt_q15_answer_2 = Answer.create(question: pt_fifteenth_question, text: "Manipulador", answer_type: "yellow")
pt_q15_answer_3 = Answer.create(question: pt_fifteenth_question, text: "Temperamental", answer_type: "green")
pt_q15_answer_4 = Answer.create(question: pt_fifteenth_question, text: "Susurras", answer_type: "blue")

pt_sixteenth_question = Question.create(test: personality_test, text: "")
pt_q16_answer_1 = Answer.create(question: pt_sixteenth_question, text: "Exhibicionista", answer_type: "red")
pt_q16_answer_2 = Answer.create(question: pt_sixteenth_question, text: "Terco", answer_type: "yellow")
pt_q16_answer_3 = Answer.create(question: pt_sixteenth_question, text: "Escéptico", answer_type: "green")
pt_q16_answer_4 = Answer.create(question: pt_sixteenth_question, text: "Lento", answer_type: "blue")

pt_seventeenth_question = Question.create(test: personality_test, text: "")
pt_q17_answer_1 = Answer.create(question: pt_seventeenth_question, text: "Gritón", answer_type: "red")
pt_q17_answer_2 = Answer.create(question: pt_seventeenth_question, text: "Autoritario", answer_type: "yellow")
pt_q17_answer_3 = Answer.create(question: pt_seventeenth_question, text: "Solitario", answer_type: "green")
pt_q17_answer_4 = Answer.create(question: pt_seventeenth_question, text: "Flojo", answer_type: "blue")

pt_eighteenth_question = Question.create(test: personality_test, text: "")
pt_q18_answer_1 = Answer.create(question: pt_eighteenth_question, text: "Disperso", answer_type: "red")
pt_q18_answer_2 = Answer.create(question: pt_eighteenth_question, text: "Intolerante", answer_type: "yellow")
pt_q18_answer_3 = Answer.create(question: pt_eighteenth_question, text: "Desconfiado", answer_type: "green")
pt_q18_answer_4 = Answer.create(question: pt_eighteenth_question, text: "Aplatanado", answer_type: "blue")

pt_nineteenth_question = Question.create(test: personality_test, text: "")
pt_q19_answer_1 = Answer.create(question: pt_nineteenth_question, text: "Incansable", answer_type: "red")
pt_q19_answer_2 = Answer.create(question: pt_nineteenth_question, text: "Tosco", answer_type: "yellow")
pt_q19_answer_3 = Answer.create(question: pt_nineteenth_question, text: "Vengativo", answer_type: "green")
pt_q19_answer_4 = Answer.create(question: pt_nineteenth_question, text: "Desconfiado", answer_type: "blue")

pt_twentieth_question = Question.create(test: personality_test, text: "")
pt_q20_answer_1 = Answer.create(question: pt_twentieth_question, text: "Voluble", answer_type: "red")
pt_q20_answer_2 = Answer.create(question: pt_twentieth_question, text: "Criticón", answer_type: "yellow")
pt_q20_answer_3 = Answer.create(question: pt_twentieth_question, text: "Astuto", answer_type: "green")
pt_q20_answer_4 = Answer.create(question: pt_twentieth_question, text: "Conciliador", answer_type: "blue")

pt_twentyfirst_question = Question.create(test: personality_test, text: "")
pt_q21_answer_1 = Answer.create(question: pt_twentyfirst_question, text: "Expresivo", answer_type: "red")
pt_q21_answer_2 = Answer.create(question: pt_twentyfirst_question, text: "Aventurero", answer_type: "yellow")
pt_q21_answer_3 = Answer.create(question: pt_twentyfirst_question, text: "Analítico", answer_type: "green")
pt_q21_answer_4 = Answer.create(question: pt_twentyfirst_question, text: "Adaptable", answer_type: "blue")

pt_twentysecond_question = Question.create(test: personality_test, text: "")
pt_q22_answer_1 = Answer.create(question: pt_twentysecond_question, text: "Juguetón", answer_type: "red")
pt_q22_answer_2 = Answer.create(question: pt_twentysecond_question, text: "Persuasivo", answer_type: "yellow")
pt_q22_answer_3 = Answer.create(question: pt_twentysecond_question, text: "Persistente", answer_type: "green")
pt_q22_answer_4 = Answer.create(question: pt_twentysecond_question, text: "Sereno", answer_type: "blue")

pt_twentythird_question = Question.create(test: personality_test, text: "")
pt_q23_answer_1 = Answer.create(question: pt_twentythird_question, text: "Sociable", answer_type: "red")
pt_q23_answer_2 = Answer.create(question: pt_twentythird_question, text: "Decidido", answer_type: "yellow")
pt_q23_answer_3 = Answer.create(question: pt_twentythird_question, text: "Sacrificado", answer_type: "green")
pt_q23_answer_4 = Answer.create(question: pt_twentythird_question, text: "Sumiso", answer_type: "blue")

pt_twentyfourth_question = Question.create(test: personality_test, text: "")
pt_q24_answer_1 = Answer.create(question: pt_twentyfourth_question, text: "Convincente", answer_type: "red")
pt_q24_answer_2 = Answer.create(question: pt_twentyfourth_question, text: "Competitivo", answer_type: "yellow")
pt_q24_answer_3 = Answer.create(question: pt_twentyfourth_question, text: "Considerado", answer_type: "green")
pt_q24_answer_4 = Answer.create(question: pt_twentyfourth_question, text: "Controlado", answer_type: "blue")

pt_twentyfifth_question = Question.create(test: personality_test, text: "")
pt_q25_answer_1 = Answer.create(question: pt_twentyfifth_question, text: "Animador", answer_type: "red")
pt_q25_answer_2 = Answer.create(question: pt_twentyfifth_question, text: "Inventivo", answer_type: "yellow")
pt_q25_answer_3 = Answer.create(question: pt_twentyfifth_question, text: "Respetuoso", answer_type: "green")
pt_q25_answer_4 = Answer.create(question: pt_twentyfifth_question, text: "Reservado", answer_type: "blue")

pt_twentysixth_question = Question.create(test: personality_test, text: "")
pt_q26_answer_1 = Answer.create(question: pt_twentysixth_question, text: "Alegre", answer_type: "red")
pt_q26_answer_2 = Answer.create(question: pt_twentysixth_question, text: "Autosuficiente", answer_type: "yellow")
pt_q26_answer_3 = Answer.create(question: pt_twentysixth_question, text: "Metódico", answer_type: "green")
pt_q26_answer_4 = Answer.create(question: pt_twentysixth_question, text: "Sensible", answer_type: "blue")

pt_twentyseventh_question = Question.create(test: personality_test, text: "")
pt_q27_answer_1 = Answer.create(question: pt_twentyseventh_question, text: "Promotor", answer_type: "red")
pt_q27_answer_2 = Answer.create(question: pt_twentyseventh_question, text: "Positivo", answer_type: "yellow")
pt_q27_answer_3 = Answer.create(question: pt_twentyseventh_question, text: "Planificador", answer_type: "green")
pt_q27_answer_4 = Answer.create(question: pt_twentyseventh_question, text: "Paciente", answer_type: "blue")

pt_twentyeighth_question = Question.create(test: personality_test, text: "")
pt_q28_answer_1 = Answer.create(question: pt_twentyeighth_question, text: "Espontáneo", answer_type: "red")
pt_q28_answer_2 = Answer.create(question: pt_twentyeighth_question, text: "Seguro", answer_type: "yellow")
pt_q28_answer_3 = Answer.create(question: pt_twentyeighth_question, text: "Organizado", answer_type: "green")
pt_q28_answer_4 = Answer.create(question: pt_twentyeighth_question, text: "Tímido", answer_type: "blue")

pt_twentyninth_question = Question.create(test: personality_test, text: "")
pt_q29_answer_1 = Answer.create(question: pt_twentyninth_question, text: "Optimista", answer_type: "red")
pt_q29_answer_2 = Answer.create(question: pt_twentyninth_question, text: "Extrovertido", answer_type: "yellow")
pt_q29_answer_3 = Answer.create(question: pt_twentyninth_question, text: "Ordenado", answer_type: "green")
pt_q29_answer_4 = Answer.create(question: pt_twentyninth_question, text: "Servicial", answer_type: "blue")

pt_thirtieth_question = Question.create(test: personality_test, text: "")
pt_q30_answer_1 = Answer.create(question: pt_thirtieth_question, text: "Simpático", answer_type: "red")
pt_q30_answer_2 = Answer.create(question: pt_thirtieth_question, text: "Enérgico", answer_type: "yellow")
pt_q30_answer_3 = Answer.create(question: pt_thirtieth_question, text: "Fiel", answer_type: "green")
pt_q30_answer_4 = Answer.create(question: pt_thirtieth_question, text: "Amistoso", answer_type: "blue")

pt_thirtyfirst_question = Question.create(test: personality_test, text: "")
pt_q31_answer_1 = Answer.create(question: pt_thirtyfirst_question, text: "Encantador", answer_type: "red")
pt_q31_answer_2 = Answer.create(question: pt_thirtyfirst_question, text: "Osado", answer_type: "yellow")
pt_q31_answer_3 = Answer.create(question: pt_thirtyfirst_question, text: "Detallista", answer_type: "green")
pt_q31_answer_4 = Answer.create(question: pt_thirtyfirst_question, text: "Disciplinado", answer_type: "blue")

pt_thirtysecond_question = Question.create(test: personality_test, text: "")
pt_q32_answer_1 = Answer.create(question: pt_thirtysecond_question, text: "Alegre", answer_type: "red")
pt_q32_answer_2 = Answer.create(question: pt_thirtysecond_question, text: "Seguro de ti", answer_type: "yellow")
pt_q32_answer_3 = Answer.create(question: pt_thirtysecond_question, text: "Culto", answer_type: "green")
pt_q32_answer_4 = Answer.create(question: pt_thirtysecond_question, text: "Consistente", answer_type: "blue")

pt_thirtythird_question = Question.create(test: personality_test, text: "")
pt_q33_answer_1 = Answer.create(question: pt_thirtythird_question, text: "Inspirador", answer_type: "red")
pt_q33_answer_2 = Answer.create(question: pt_thirtythird_question, text: "Independiente", answer_type: "yellow")
pt_q33_answer_3 = Answer.create(question: pt_thirtythird_question, text: "Idealista", answer_type: "green")
pt_q33_answer_4 = Answer.create(question: pt_thirtythird_question, text: "Inofensivo", answer_type: "blue")

pt_thirtyfourth_question = Question.create(test: personality_test, text: "")
pt_q34_answer_1 = Answer.create(question: pt_thirtyfourth_question, text: "Expresivo", answer_type: "red")
pt_q34_answer_2 = Answer.create(question: pt_thirtyfourth_question, text: "Decidido", answer_type: "yellow")
pt_q34_answer_3 = Answer.create(question: pt_thirtyfourth_question, text: "Profundo", answer_type: "green")
pt_q34_answer_4 = Answer.create(question: pt_thirtyfourth_question, text: "Humor seco", answer_type: "blue")

pt_thirtyfifth_question = Question.create(test: personality_test, text: "")
pt_q35_answer_1 = Answer.create(question: pt_thirtyfifth_question, text: "Sociable", answer_type: "red")
pt_q35_answer_2 = Answer.create(question: pt_thirtyfifth_question, text: "Hacedor", answer_type: "yellow")
pt_q35_answer_3 = Answer.create(question: pt_thirtyfifth_question, text: "Musical", answer_type: "green")
pt_q35_answer_4 = Answer.create(question: pt_thirtyfifth_question, text: "Mediador", answer_type: "blue")

pt_thirtysixth_question = Question.create(test: personality_test, text: "")
pt_q36_answer_1 = Answer.create(question: pt_thirtysixth_question, text: "Hablador", answer_type: "red")
pt_q36_answer_2 = Answer.create(question: pt_thirtysixth_question, text: "Tenaz", answer_type: "yellow")
pt_q36_answer_3 = Answer.create(question: pt_thirtysixth_question, text: "Considerado", answer_type: "green")
pt_q36_answer_4 = Answer.create(question: pt_thirtysixth_question, text: "Tolerante", answer_type: "blue")

pt_thirtyseventh_question = Question.create(test: personality_test, text: "")
pt_q37_answer_1 = Answer.create(question: pt_thirtyseventh_question, text: "Vivaz", answer_type: "red")
pt_q37_answer_2 = Answer.create(question: pt_thirtyseventh_question, text: "Determinante", answer_type: "yellow")
pt_q37_answer_3 = Answer.create(question: pt_thirtyseventh_question, text: "Leal", answer_type: "green")
pt_q37_answer_4 = Answer.create(question: pt_thirtyseventh_question, text: "Sabes escuchar", answer_type: "blue")

pt_thirtyeighth_question = Question.create(test: personality_test, text: "")
pt_q38_answer_1 = Answer.create(question: pt_thirtyeighth_question, text: "Simpático", answer_type: "red")
pt_q38_answer_2 = Answer.create(question: pt_thirtyeighth_question, text: "Atrevido", answer_type: "yellow")
pt_q38_answer_3 = Answer.create(question: pt_thirtyeighth_question, text: "Estructurado", answer_type: "green")
pt_q38_answer_4 = Answer.create(question: pt_thirtyeighth_question, text: "Tierno", answer_type: "blue")

pt_thirtyninth_question = Question.create(test: personality_test, text: "")
pt_q39_answer_1 = Answer.create(question: pt_thirtyninth_question, text: "Popular", answer_type: "red")
pt_q39_answer_2 = Answer.create(question: pt_thirtyninth_question, text: "Súper líder", answer_type: "yellow")
pt_q39_answer_3 = Answer.create(question: pt_thirtyninth_question, text: "Perfeccionista", answer_type: "green")
pt_q39_answer_4 = Answer.create(question: pt_thirtyninth_question, text: "Agradable", answer_type: "blue")

pt_fourtieth_question = Question.create(test: personality_test, text: "")
pt_q40_answer_1 = Answer.create(question: pt_fourtieth_question, text: "Feliz", answer_type: "red")
pt_q40_answer_2 = Answer.create(question: pt_fourtieth_question, text: "Atrevido", answer_type: "yellow")
pt_q40_answer_3 = Answer.create(question: pt_fourtieth_question, text: "Diplomático", answer_type: "green")
pt_q40_answer_4 = Answer.create(question: pt_fourtieth_question, text: "Equilibrado", answer_type: "blue")

#Test del módulo 1
test_modulo_1 = Test.create(name: "Módulo uno", test_type: "correct_incorrect", code: "module_1")
tm1_question_1 = Question.create(test: test_modulo_1, text: "¿Cuántos fundadores tiene Xango y de qué industria provienen todos?")
tm1_q1_answer_1 = Answer.create(question: tm1_question_1, text:"Son 5, provienen del mundo financiero", answer_type: "incorrect")
tm1_q1_answer_2 = Answer.create(question: tm1_question_1, text:"Son 6, provienen de otras empresas de redes", answer_type: "correct")
tm1_q1_answer_3 = Answer.create(question: tm1_question_1, text:"Son 4, provienen de empresas de venta directa", answer_type: "incorrect")
tm1_q1_answer_4 = Answer.create(question: tm1_question_1, text:"Son 6, provienen de distintas industrias", answer_type: "incorrect")

tm1_question_2 = Question.create(test: test_modulo_1, text: "¿En qué año arrancó operaciones la empresa?")
tm1_q2_answer_1 = Answer.create(question: tm1_question_2, text:"2000", answer_type: "incorrect")
tm1_q2_answer_2 = Answer.create(question: tm1_question_2, text:"2002", answer_type: "correct")
tm1_q2_answer_3 = Answer.create(question: tm1_question_2, text:"2003", answer_type: "incorrect")
tm1_q2_answer_4 = Answer.create(question: tm1_question_2, text:"2005", answer_type: "incorrect")

tm1_question_3 = Question.create(test: test_modulo_1, text: "¿A cuánto ascienden las ventas acumuladas de Xango?")
tm1_q3_answer_1 = Answer.create(question: tm1_question_3, text:"1000 millones de dólares", answer_type: "incorrect")
tm1_q3_answer_2 = Answer.create(question: tm1_question_3, text:"600 millones de dólares", answer_type: "incorrect")
tm1_q3_answer_3 = Answer.create(question: tm1_question_3, text:"2000 millones de dólares", answer_type: "correct")
tm1_q3_answer_4 = Answer.create(question: tm1_question_3, text:"1200 millones de dólares", answer_type: "incorrect")

tm1_question_4 = Question.create(test: test_modulo_1, text: "¿De cuántas personas es recomendable hacer la lista de prospectos?")
tm1_q4_answer_1 = Answer.create(question: tm1_question_4, text:"de los más posibles", answer_type: "incorrect")
tm1_q4_answer_2 = Answer.create(question: tm1_question_4, text:"de 15", answer_type: "incorrect")
tm1_q4_answer_3 = Answer.create(question: tm1_question_4, text:"de más de 25", answer_type: "correct")
tm1_q4_answer_4 = Answer.create(question: tm1_question_4, text:"de 100 por lo menos", answer_type: "incorrect")

tm1_question_5 = Question.create(test: test_modulo_1, text: "¿De dónde debo obtener mi lista de prospectos?")
tm1_q5_answer_1 = Answer.create(question: tm1_question_5, text:"de mi círculo de influencia", answer_type: "correct")
tm1_q5_answer_2 = Answer.create(question: tm1_question_5, text:"de crear una página web", answer_type: "incorrect")
tm1_q5_answer_3 = Answer.create(question: tm1_question_5, text:"mi patrocinador me la dará", answer_type: "incorrect")
tm1_q5_answer_4 = Answer.create(question: tm1_question_5, text:"de poner anuncios en periódicos y bolsas de trabajo", answer_type: "incorrect")

tm1_question_6 = Question.create(test: test_modulo_1, text: "¿Qué debo evitar al llamar a mis prospectos?")
tm1_q6_answer_1 = Answer.create(question: tm1_question_6, text:"resolver todas sus preguntas", answer_type: "incorrect")
tm1_q6_answer_2 = Answer.create(question: tm1_question_6, text:"tener una charla social", answer_type: "incorrect")
tm1_q6_answer_3 = Answer.create(question: tm1_question_6, text:"que se queden intrigados", answer_type: "incorrect")
tm1_q6_answer_4 = Answer.create(question: tm1_question_6, text:"1 y 2", answer_type: "correct")

tm1_question_7 = Question.create(test: test_modulo_1, text: "¿Qué debo hacer al llamar a mis prospectos?")
tm1_q7_answer_1 = Answer.create(question: tm1_question_7, text:"despertar su curiosidad", answer_type: "incorrect")
tm1_q7_answer_2 = Answer.create(question: tm1_question_7, text:"hacerles un elogio sincero", answer_type: "incorrect")
tm1_q7_answer_3 = Answer.create(question: tm1_question_7, text:"decir que tienes prisa", answer_type: "incorrect")
tm1_q7_answer_4 = Answer.create(question: tm1_question_7, text:"todas las anteriores", answer_type: "correct")

tm1_question_8 = Question.create(test: test_modulo_1, text: "¿Cuál es uno de los retos más fuertes que implica este proyecto?")
tm1_q8_answer_1 = Answer.create(question: tm1_question_8, text:"sobrepasar los no", answer_type: "correct")
tm1_q8_answer_2 = Answer.create(question: tm1_question_8, text:"aprender todo sobre la fruta", answer_type: "incorrect")
tm1_q8_answer_3 = Answer.create(question: tm1_question_8, text:"hacer correctamente la lista", answer_type: "incorrect")
tm1_q8_answer_4 = Answer.create(question: tm1_question_8, text:"lograr que la gente se tome el jugo", answer_type: "incorrect")

tm1_question_9 = Question.create(test: test_modulo_1, text: "¿A qué llamamos edificación? ")
tm1_q9_answer_1 = Answer.create(question: tm1_question_9, text:"a construir un negocio sólido", answer_type: "incorrect")
tm1_q9_answer_2 = Answer.create(question: tm1_question_9, text:"a no quejarse", answer_type: "incorrect")
tm1_q9_answer_3 = Answer.create(question: tm1_question_9, text:"a hablar bien de alguien", answer_type: "correct")
tm1_q9_answer_4 = Answer.create(question: tm1_question_9, text:"a tener bien estructurado el grupo", answer_type: "incorrect")

tm1_question_10 = Question.create(test: test_modulo_1, text: "¿Qué herramienta de capacitación me ofrece iuvare?")
tm1_q10_answer_1 = Answer.create(question: tm1_question_10, text:"cursos en el extranjero", answer_type: "incorrect")
tm1_q10_answer_2 = Answer.create(question: tm1_question_10, text:"visitas de líderes a mi casa", answer_type: "incorrect")
tm1_q10_answer_3 = Answer.create(question: tm1_question_10, text:"suscripción a revistas especializadas", answer_type: "incorrect")
tm1_q10_answer_4 = Answer.create(question: tm1_question_10, text:"ninguna de las anteriores", answer_type: "correct")

#Test del módulo 2
test_modulo_2 = Test.create(name: "Módulo dos", test_type: "correct_incorrect", code: "module_2")
tm2_question_1 = Question.create(test: test_modulo_2, text: "¿Cuáles son los 2 parámetros que se deben cuplir para ir calificando en XanGo?")
tm2_q1_answer_1 = Answer.create(question: tm2_question_1, text:"Entusiasmo y volumen", answer_type: "incorrect")
tm2_q1_answer_2 = Answer.create(question: tm2_question_1, text:"Estructura y volumen", answer_type: "correct")
tm2_q1_answer_3 = Answer.create(question: tm2_question_1, text:"Sólo estructura", answer_type: "incorrect")
tm2_q1_answer_4 = Answer.create(question: tm2_question_1, text:"Sólo volumen", answer_type: "incorrect")

tm2_question_2 = Question.create(test: test_modulo_2, text: "¿Cómo funciona el patrocinio y la colocación en tu organización?")
tm2_q2_answer_1 = Answer.create(question: tm2_question_2, text:"Patrocinio te da calificación y colocación volumen", answer_type: "correct")
tm2_q2_answer_2 = Answer.create(question: tm2_question_2, text:"Patrocinio son los puntos de mi volumen de grupo", answer_type: "incorrect")
tm2_q2_answer_3 = Answer.create(question: tm2_question_2, text:"Patrocinio te da volumen y colocación te da calificación", answer_type: "incorrect")
tm2_q2_answer_4 = Answer.create(question: tm2_question_2, text:"Ninguna de las anteriores", answer_type: "incorrect")

tm2_question_3 = Question.create(test: test_modulo_2, text: "¿En iuvare cómo es que garantizas que siempre vas a cobrar del socio clave?")
tm2_q3_answer_1 = Answer.create(question: tm2_question_3, text:"Porque sólo regalo mi consumo personal a mi upline", answer_type: "incorrect")
tm2_q3_answer_2 = Answer.create(question: tm2_question_3, text:"Porque regalo el patrocinio y la colocación a mi upline", answer_type: "incorrect")
tm2_q3_answer_3 = Answer.create(question: tm2_question_3, text:"Porque sólo regalo el patrocinio a mi upline y yo mantengo la colocación", answer_type: "correct")
tm2_q3_answer_4 = Answer.create(question: tm2_question_3, text:"Por todas las anteriores", answer_type: "incorrect")

tm2_question_4 = Question.create(test: test_modulo_2, text: "¿Cuáles son los requisitos mínimos para calificar como 1K?")
tm2_q4_answer_1 = Answer.create(question: tm2_question_4, text:"Ocho frontales y un volumen de grupo de 8 cajas", answer_type: "incorrect")
tm2_q4_answer_2 = Answer.create(question: tm2_question_4, text:"Dos frontales y un volumen 12 cajas", answer_type: "incorrect")
tm2_q4_answer_3 = Answer.create(question: tm2_question_4, text:"Tres frontales y un volumen de 10 cajas", answer_type: "correct")
tm2_q4_answer_4 = Answer.create(question: tm2_question_4, text:"Únicamente con un volumen personal de 10 cajas", answer_type: "incorrect")

tm2_question_5 = Question.create(test: test_modulo_2, text: "¿Cuáles son los requisitos para calificar como Premier 50K?")
tm2_q5_answer_1 = Answer.create(question: tm2_question_5, text:"Mínimo 3 patrocinados directos como 20K y uno como 5K y un volumen de 1000 cajas", answer_type: "incorrect")
tm2_q5_answer_2 = Answer.create(question: tm2_question_5, text:"Mínimo 2 patrocinados directos como Premier 200K y dos como 5K y un volumen de 500 cajas", answer_type: "incorrect")
tm2_q5_answer_3 = Answer.create(question: tm2_question_5, text:"Mínimo 2 patrocinados directos como 20K y dos como 5K y un volumen de 5000 puntos", answer_type: "incorrect")
tm2_q5_answer_4 = Answer.create(question: tm2_question_5, text:"Mínimo 2 patrocinados directos como 20K y uno como 5K y un volumen de 500 cajas", answer_type: "correct")

tm2_question_6 = Question.create(test: test_modulo_2, text: "¿Qué porcentaje reparte XanGo del consumo de cada producto entre sus distribuidores?")
tm2_q6_answer_1 = Answer.create(question: tm2_question_6, text:"50%", answer_type: "correct")
tm2_q6_answer_2 = Answer.create(question: tm2_question_6, text:"Al infinito", answer_type: "incorrect")
tm2_q6_answer_3 = Answer.create(question: tm2_question_6, text:"7%", answer_type: "incorrect")
tm2_q6_answer_4 = Answer.create(question: tm2_question_6, text:"15%", answer_type: "incorrect")

tm2_question_7 = Question.create(test: test_modulo_2, text: "¿Cuántos niveles paga XanGo en comisiones?")
tm2_q7_answer_1 = Answer.create(question: tm2_question_7, text:"1 nivel", answer_type: "incorrect")
tm2_q7_answer_2 = Answer.create(question: tm2_question_7, text:"9 niveles", answer_type: "correct")
tm2_q7_answer_3 = Answer.create(question: tm2_question_7, text:"3 niveles", answer_type: "incorrect")
tm2_q7_answer_4 = Answer.create(question: tm2_question_7, text:"2 niveles", answer_type: "incorrect")

tm2_question_8 = Question.create(test: test_modulo_2, text: "¿Cuál es el porcentaje que paga XanGo en un tercer nivel?")
tm2_q8_answer_1 = Answer.create(question: tm2_question_8, text:"5%", answer_type: "incorrect")
tm2_q8_answer_2 = Answer.create(question: tm2_question_8, text:"6%", answer_type: "incorrect")
tm2_q8_answer_3 = Answer.create(question: tm2_question_8, text:"8%", answer_type: "incorrect")
tm2_q8_answer_4 = Answer.create(question: tm2_question_8, text:"10%", answer_type: "correct")

tm2_question_9 = Question.create(test: test_modulo_2, text: "¿Cuánto te pagan por power start de tus frontales?")
tm2_q9_answer_1 = Answer.create(question: tm2_question_9, text:"30%", answer_type: "correct")
tm2_q9_answer_2 = Answer.create(question: tm2_question_9, text:"50%", answer_type: "incorrect")
tm2_q9_answer_3 = Answer.create(question: tm2_question_9, text:"Nada", answer_type: "incorrect")
tm2_q9_answer_4 = Answer.create(question: tm2_question_9, text:"100%", answer_type: "incorrect")

tm2_question_10 = Question.create(test: test_modulo_2, text: "¿Cuánto reparte XanGo en donaciones?")
tm2_q10_answer_1 = Answer.create(question: tm2_question_10, text:"Todo", answer_type: "incorrect")
tm2_q10_answer_2 = Answer.create(question: tm2_question_10, text:"Nada", answer_type: "incorrect")
tm2_q10_answer_3 = Answer.create(question: tm2_question_10, text:"7%", answer_type: "correct")
tm2_q10_answer_4 = Answer.create(question: tm2_question_10, text:"18%", answer_type: "incorrect")

#Test del módulo 3
test_modulo_3 = Test.create(name: "Módulo tres", test_type: "correct_incorrect", code: "module_3")
tm3_question_1 = Question.create(test: test_modulo_3, text: "¿Cuál es el nombre científico del mangostán?")
tm3_q1_answer_1 = Answer.create(question: tm3_question_1, text:"Mangostana Garcinia", answer_type: "incorrect")
tm3_q1_answer_2 = Answer.create(question: tm3_question_1, text:"Garcinia Mangostana", answer_type: "correct")
tm3_q1_answer_3 = Answer.create(question: tm3_question_1, text:"Laurentis Garcín", answer_type: "incorrect")

tm3_question_2 = Question.create(test: test_modulo_3, text: "¿Cuál de estas frutas no se utiliza en el jugo Xango?")
tm3_q2_answer_1 = Answer.create(question: tm3_question_2, text:"Pera", answer_type: "incorrect")
tm3_q2_answer_2 = Answer.create(question: tm3_question_2, text:"Manzana", answer_type: "incorrect")
tm3_q2_answer_3 = Answer.create(question: tm3_question_2, text:"Ciruela", answer_type: "correct")

tm3_question_3 = Question.create(test: test_modulo_3, text: "La empresa con la que Xango se asoció para producir el jugo se llama:")
tm3_q3_answer_1 = Answer.create(question: tm3_question_3, text:"Flavors International", answer_type: "incorrect")
tm3_q3_answer_2 = Answer.create(question: tm3_question_3, text:"Wild Flavors", answer_type: "correct")
tm3_q3_answer_3 = Answer.create(question: tm3_question_3, text:"Thailand Flavors", answer_type: "incorrect")

tm3_question_4 = Question.create(test: test_modulo_3, text: "La proteína C reactiva es un indicador de")
tm3_q4_answer_1 = Answer.create(question: tm3_question_4, text:"Inflamación", answer_type: "correct")
tm3_q4_answer_2 = Answer.create(question: tm3_question_4, text:"Toxicidad", answer_type: "incorrect")
tm3_q4_answer_3 = Answer.create(question: tm3_question_4, text:"Oxidación", answer_type: "incorrect")

tm3_question_5 = Question.create(test: test_modulo_3, text: "¿Qué quiere decir pansistémico?")
tm3_q5_answer_1 = Answer.create(question: tm3_question_5, text:"Que funciona específicamente en un sistema", answer_type: "incorrect")
tm3_q5_answer_2 = Answer.create(question: tm3_question_5, text:"Que no funciona en ningún sistema", answer_type: "incorrect")
tm3_q5_answer_3 = Answer.create(question: tm3_question_5, text:"Que funciona en diferentes sistemas", answer_type: "correct")

tm3_question_6 = Question.create(test: test_modulo_3, text: "El jugo Xango ¿contiene estilbenos?")
tm3_q6_answer_1 = Answer.create(question: tm3_question_6, text:"Si", answer_type: "correct")
tm3_q6_answer_2 = Answer.create(question: tm3_question_6, text:"No", answer_type: "incorrect")

tm3_question_7 = Question.create(test: test_modulo_3, text: "El jugo Xango ¿contiene Omega 3?")
tm3_q7_answer_1 = Answer.create(question: tm3_question_7, text:"Si", answer_type: "incorrect")
tm3_q7_answer_2 = Answer.create(question: tm3_question_7, text:"No", answer_type: "correct")

tm3_question_8 = Question.create(test: test_modulo_3, text: "La dosis mínima sugerida de jugo Xango es de")
tm3_q8_answer_1 = Answer.create(question: tm3_question_8, text:"3 onzas diarias", answer_type: "incorrect")
tm3_q8_answer_2 = Answer.create(question: tm3_question_8, text:"2 onzas diarias", answer_type: "correct")
tm3_q8_answer_3 = Answer.create(question: tm3_question_8, text:"1 onza diaria", answer_type: "incorrect")

tm3_question_9 = Question.create(test: test_modulo_3, text: "El jugo Xango ¿lo pueden tomar personas con Púrpura?")
tm3_q9_answer_1 = Answer.create(question: tm3_question_9, text:"Si", answer_type: "correct")
tm3_q9_answer_2 = Answer.create(question: tm3_question_9, text:"No", answer_type: "incorrect")

tm3_question_10 = Question.create(test: test_modulo_3, text: "¿Qué porcentaje de las personas que toman el jugo Xango presentan crisis curativa?")
tm3_q10_answer_1 = Answer.create(question: tm3_question_10, text:"1%", answer_type: "correct")
tm3_q10_answer_2 = Answer.create(question: tm3_question_10, text:"5%", answer_type: "incorrect")
tm3_q10_answer_3 = Answer.create(question: tm3_question_10, text:"7%", answer_type: "incorrect")

#Test del taller de arranque
test_basics = Test.create(name: "Taller de arranque", test_type: "correct_incorrect", code: "basics")
tb_question_1 = Question.create(test: test_basics, text: "¿Qué determina el tamaño de tu contexto (árbol)?")
tb_q1_answer_1 = Answer.create(question: tb_question_1, text:"tus metas y deseos", answer_type: "incorrect")
tb_q1_answer_2 = Answer.create(question: tb_question_1, text:"el tamaño de tus sueños y la espectativa que tengas", answer_type: "correct")
tb_q1_answer_3 = Answer.create(question: tb_question_1, text:"las habilidades interpersonales que generas", answer_type: "incorrect")
tb_q1_answer_4 = Answer.create(question: tb_question_1, text:"cursos de desarrollo personal", answer_type: "incorrect")

tb_question_2 = Question.create(test: test_basics, text: "¿Cómo puedo alimentar mi contexto?")
tb_q2_answer_1 = Answer.create(question: tb_question_2, text:"Yendo a cursos de desarrollo personal cada mes para aprender nuevas habilidades", answer_type: "incorrect")
tb_q2_answer_2 = Answer.create(question: tb_question_2, text:"Con un coach personal que me ayude a estirarme y a subir mi propio estándar", answer_type: "incorrect")
tb_q2_answer_3 = Answer.create(question: tb_question_2, text:"alimentando mi certeza rodeándote de la gente correcta, escuchando cds, libros, seminarios y convenciones", answer_type: "correct")
tb_q2_answer_4 = Answer.create(question: tb_question_2, text:"Yendo diario al plan", answer_type: "incorrect")

tb_question_3 = Question.create(test: test_basics, text: "¿Cuál es la piedra angular de nuestro negocio?")
tb_q3_answer_1 = Answer.create(question: tb_question_3, text:"La certeza", answer_type: "correct")
tb_q3_answer_2 = Answer.create(question: tb_question_3, text:"el Jugo", answer_type: "incorrect")
tb_q3_answer_3 = Answer.create(question: tb_question_3, text:"el plan de compensacion", answer_type: "incorrect")
tb_q3_answer_4 = Answer.create(question: tb_question_3, text:"el mangostán", answer_type: "incorrect")

tb_question_4 = Question.create(test: test_basics, text: "¿Quién es responsable de lo que pasa en tu negocio?")
tb_q4_answer_1 = Answer.create(question: tb_question_4, text:"Yo", answer_type: "correct")
tb_q4_answer_2 = Answer.create(question: tb_question_4, text:"mi upline", answer_type: "incorrect")
tb_q4_answer_3 = Answer.create(question: tb_question_4, text:"mis downlines", answer_type: "incorrect")
tb_q4_answer_4 = Answer.create(question: tb_question_4, text:"los premiers de Iuvare", answer_type: "incorrect")

tb_question_5 = Question.create(test: test_basics, text: "¿Cuál de las siguientes actividades no es un punto medular para poder trabajar efectivamente?")
tb_q5_answer_1 = Answer.create(question: tb_question_5, text:"Agendar tiempo especifico para mi negocio", answer_type: "incorrect")
tb_q5_answer_2 = Answer.create(question: tb_question_5, text:"Hacer una lista de todo mundo", answer_type: "incorrect")
tb_q5_answer_3 = Answer.create(question: tb_question_5, text:"Hacer mi Collage", answer_type: "correct")
tb_q5_answer_4 = Answer.create(question: tb_question_5, text:"Ir al plan", answer_type: "incorrect")

tb_question_6 = Question.create(test: test_basics, text: "¿Cuál de estos no es un paso para la duplicación?")
tb_q6_answer_1 = Answer.create(question: tb_question_6, text:"Yo hago tu observas", answer_type: "incorrect")
tb_q6_answer_2 = Answer.create(question: tb_question_6, text:"Tu lo haces y yo observo", answer_type: "incorrect")
tb_q6_answer_3 = Answer.create(question: tb_question_6, text:"Lo hacemos juntos", answer_type: "incorrect")
tb_q6_answer_4 = Answer.create(question: tb_question_6, text:"Nos juntamos para hacer todo en equipo", answer_type: "correct")

tb_question_7 = Question.create(test: test_basics, text: "¿Cuál de los siguientes no es un tipo de  invitación?")
tb_q7_answer_1 = Answer.create(question: tb_question_7, text:"Invitación directa", answer_type: "incorrect")
tb_q7_answer_2 = Answer.create(question: tb_question_7, text:"Invitación en persona", answer_type: "correct")
tb_q7_answer_3 = Answer.create(question: tb_question_7, text:"Invitación de expansión de negocios", answer_type: "incorrect")
tb_q7_answer_4 = Answer.create(question: tb_question_7, text:"invitación indirecta", answer_type: "incorrect")

tb_question_8 = Question.create(test: test_basics, text: "¿A la hora de hacer una invitacion mi trabajo es?")
tb_q8_answer_1 = Answer.create(question: tb_question_8, text:"Convencer a las personas que tienen que ver lo que estoy haciendo", answer_type: "incorrect")
tb_q8_answer_2 = Answer.create(question: tb_question_8, text:"Traerlos a rastras para que vean el plan", answer_type: "incorrect")
tb_q8_answer_3 = Answer.create(question: tb_question_8, text:"Ponerle la postura de que quizás si califican los van a escoger", answer_type: "correct")

tb_question_9 = Question.create(test: test_basics, text: "¿Qué debes de hacer cuando alguien de cancela una cita?")
tb_q9_answer_1 = Answer.create(question: tb_question_9, text:"Dales las gracias por su tiempo", answer_type: "incorrect")
tb_q9_answer_2 = Answer.create(question: tb_question_9, text:"Reagenda en ese momento", answer_type: "correct")
tb_q9_answer_3 = Answer.create(question: tb_question_9, text:"Queda en llamarles despues para reagendar en otra ocasión", answer_type: "incorrect")
tb_q9_answer_4 = Answer.create(question: tb_question_9, text:"Regáñalos por no haber cumplido su palabra", answer_type: "incorrect")

tb_question_10 = Question.create(test: test_basics, text: "¿Durante el preplán nuestro trabajo es?")
tb_q10_answer_1 = Answer.create(question: tb_question_10, text:"Convencer y hacer que tengan ganas de ver el negocio", answer_type: "incorrect")
tb_q10_answer_2 = Answer.create(question: tb_question_10, text:"Crear expectativa, y motivar a nuestros downlines", answer_type: "incorrect")
tb_q10_answer_3 = Answer.create(question: tb_question_10, text:"Filtrar edificar, y crear expectativa", answer_type: "correct")
tb_q10_answer_4 = Answer.create(question: tb_question_10, text:"Otra", answer_type: "incorrect")

tb_question_11 = Question.create(test: test_basics, text: "¿Qué es lo mas importante que tienes que saber para tener éxito?")
tb_q11_answer_1 = Answer.create(question: tb_question_11, text:"Conocer perfectamente el plan de negocios", answer_type: "incorrect")
tb_q11_answer_2 = Answer.create(question: tb_question_11, text:"Conocer perfectamente el jugo", answer_type: "incorrect")
tb_q11_answer_3 = Answer.create(question: tb_question_11, text:"Conocer al prospecto", answer_type: "correct")

tb_question_12 = Question.create(test: test_basics, text: "A la hora del cierre")
tb_q12_answer_1 = Answer.create(question: tb_question_12, text:"La clave es darle información al prospecto", answer_type: "incorrect")
tb_q12_answer_2 = Answer.create(question: tb_question_12, text:"Explicarle perfectamente el plan de compensación", answer_type: "incorrect")
tb_q12_answer_3 = Answer.create(question: tb_question_12, text:"Hacer preguntas y escuchar y de preferencia dejar que mi upline me ayude", answer_type: "correct")
tb_q12_answer_4 = Answer.create(question: tb_question_12, text:"Ninguna de las anteriores", answer_type: "incorrect")

#Test despues del plan
test_plan = Test.create(name: "Plan", test_type: "multiple", code: "plan")
tb_question_1 = Question.create(test: test_plan, text: "En una escala del 1 al 10, ¿qué nivel de interés despertó en ti la propuesta? (Siendo 1 ningún interés y 10 un gran interés)")
tp_q1_answer_1 = Answer.create(question: tb_question_1, text:"1")
tp_q1_answer_2 = Answer.create(question: tb_question_1, text:"2")
tp_q1_answer_3 = Answer.create(question: tb_question_1, text:"3")
tp_q1_answer_4 = Answer.create(question: tb_question_1, text:"4")
tp_q1_answer_5 = Answer.create(question: tb_question_1, text:"5")
tp_q1_answer_6 = Answer.create(question: tb_question_1, text:"6")
tp_q1_answer_7 = Answer.create(question: tb_question_1, text:"7")
tp_q1_answer_8 = Answer.create(question: tb_question_1, text:"8")
tp_q1_answer_9 = Answer.create(question: tb_question_1, text:"9")
tp_q1_answer_10 = Answer.create(question: tb_question_1, text:"10")

tp_question_2 = Question.create(test: test_plan, text: "¿En qué momento te gustaría que me ponga en contacto contigo?")
tp_q2_answer_1 = Answer.create(question: tp_question_2, text:"Hoy")
tp_q2_answer_2 = Answer.create(question: tp_question_2, text:"Mañana")
tp_q2_answer_3 = Answer.create(question: tp_question_2, text:"No es necesario")

#Assets
# Convencion de nombres [asset_type]_[author]_[title]
# ASSET_TYPES = ['audio', 'seminar', 'convention', 'training', 'document', 'plan']
#asset_type = audio

asset_0 = Asset.create(title: "El enfoque", description: " ", author: "Alexis Budd", source: "audio_Alexis_Budd_El_enfoque.mp3", asset_type: "audio")
asset_1 = Asset.create(title: "Atrévete cambia", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Atrevete_cambia.mp3", asset_type: "audio")
asset_2 = Asset.create(title: "Libertad financiera", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Libertad_financiera.mp3", asset_type: "audio")
asset_3 = Asset.create(title: "Simplifica tu negocio", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Simplifica_tu_negocio.mp3", asset_type: "audio")
#asset_4 = Asset.create(title: "El secreto del millon de dolares", description: " ", author: "David Butler", source: "audio_David_Butler_El_secreto_del_millon_de_dolares.mp3", asset_type: "audio")
asset_5 = Asset.create(title: "Seminario 18 de junio 2011", description: " ", author: "Dr Pepe Cruz", source: "audio_Dr_Pepe_Cruz_Seminario_18_de_junio_2011.mp3", asset_type: "audio")
asset_6 = Asset.create(title: "Excusas y creencias", description: " ", author: "Enrique Flores", source: "audio_Enrique_Flores_Excusas_y_creencias.mp3", asset_type: "audio")
asset_7 = Asset.create(title: "Básicos 1", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Basicos 1.mp3", asset_type: "audio")
asset_8 = Asset.create(title: "Básicos 2", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Basicos 2.mp3", asset_type: "audio")
asset_9 = Asset.create(title: "Buscando el colorín", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Buscando_el_colorin.mp3", asset_type: "audio")
asset_10 = Asset.create(title: "Las reglas del juego", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Las_reglas_del_juego.mp3", asset_type: "audio")
asset_11 = Asset.create(title: "Placer y dolor", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Placer_y_dolor.mp3", asset_type: "audio")
asset_12 = Asset.create(title: "¿Por qué un collage?", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Por_que_un_collage.mp3", asset_type: "audio")
asset_13 = Asset.create(title: "Sé el dueño de tu vida", description: " ", author: "Estela Salinas", source: "audio_Estela_Salinas_Se_el_dueno_de_tu_vida.mp3", asset_type: "audio")
asset_13_1 = Asset.create(title: "Como prospectar", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Como_prospectar.mp3", asset_type: "audio")
asset_13_2 = Asset.create(title: "Proceso de cierre", description: " ", author: "Circe Rodríguez", source: "audio_Circe_Rodriguez_Proceso_de_cierre.mp3", asset_type: "audio")

#asset_14 = Asset.create(title: "El cierre 1", description: " ", author: "Iuvare", source: "audio_Iuvare_El_cierre_1.mp3", asset_type: "audio")
#asset_15 = Asset.create(title: "El cierre 2", description: " ", author: "Iuvare", source: "audio_Iuvare_El_cierre_2.mp3", asset_type: "audio")
#asset_16 = Asset.create(title: "El cierre 3", description: " ", author: "Iuvare", source: "audio_Iuvare_El_cierre_3.mp3", asset_type: "audio")
asset_17 = Asset.create(title: "Administración del tiempo", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Administracion_del_tiempo.mp3", asset_type: "audio")
asset_18 = Asset.create(title: "El crossline", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_El_crossline.mp3", asset_type: "audio")
asset_19 = Asset.create(title: "Eres extra o protagonista", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Eres_extra_o_protagonista.mp3", asset_type: "audio")
asset_20 = Asset.create(title: "Libros indispensables", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Libros_indispensables.mp3", asset_type: "audio")
asset_21 = Asset.create(title: "Una magnífica opción ante la crisis", description: " ", author: "Jorge Arzamendi", source: "audio_Jorge_Arzamendi_Una_magnifica_opcion_ante_la_crisis.mp3", asset_type: "audio")
asset_22 = Asset.create(title: "La importancia de tener un sueño", description: " ", author: "Liz Salinas", source: "audio_Liz_Salinas_La_importancia_de_tener_un_sueno.mp3", asset_type: "audio")
asset_23 = Asset.create(title: "Toma acción", description: " ", author: "Marcela Flores", source: "audio_Marcela_Flores_Toma_accion.mp3", asset_type: "audio")
#asset_24 = Asset.create(title: "El cierre", description: " ", author: "Marco Galbiati", source: "audio_Marco_Galbiati_El_cierre.mp3", asset_type: "audio")
#asset_25 = Asset.create(title: "La lista del miedo", description: " ", author: "Marco Galbiati", source: "audio_Marco_Galbiati_La_lista_del_miedo.mp3", asset_type: "audio")
asset_26 = Asset.create(title: "La edificación", description: " ", author: "Marisa Dodero", source: "audio_Marisa_Dodero_La_edificacion.mp3", asset_type: "audio")
asset_27 = Asset.create(title: "Liderazgo", description: " ", author: "Raul Villegas", source: "audio_Raul_Villegas_Liderazgo.mp3", asset_type: "audio")
#asset_28 = Asset.create(title: "Como generar riqueza", description: " ", author: "Raul y Rocio Galindo", source: "audio_Raul_y_Rocio_Galindo_Como_generar_riqueza.mp3", asset_type: "audio")

#asset_type = document

asset_29 = Asset.create(title: "Contrato de distribuidor", description: "Formato que necesitas enviar a XanGo para registrar un nuevo socio", author: "Xango", source: "document_Xango_Contrato_de_distribuidor.pdf", asset_type: "document")
asset_30 = Asset.create(title: "Hoja de Cambio de Patrocinio/Colocación", description: "Con este formato puedes hacer cambios en el patrocinio y/o colocación de tus socios", author: "Xango", source: "document_Xango_Solicitud_de_cambio_de_patrocinio.pdf", asset_type: "document")
asset_31 = Asset.create(title: "Aaron Garrity ceo of the year", description: "Imagen de la revista Utah Business Magazine", author: "Xango", source: "document_Xango_Aaron_Garrity_ceo_of_the_year.pdf", asset_type: "document")
asset_32 = Asset.create(title: "Patente Xango", description: "Documento donde podrás leer sobre la patente de Xango", author: "Xango", source: "document_Xango_Patente_Xango.pdf", asset_type: "document")

asset_33 = Asset.create(title: "Reglamento Iuvare", description: "Aquí puedes leer más acerca de las reglas de la metodología", author: "Iuvare", source: "document_Iuvare_Reglamento_Iuvare.pdf", asset_type: "document")
asset_34_ = Asset.create(title: "Plan de Compensación", description: "Plan de compensación BOLD", author: "Xango", source: "document_Xango_plan_de_compensacion.pdf", asset_type: "document")
#asset_34 = Asset.create(title: "iBonus", description: "Generales del programa iBonus", author: "Xango", source: "document_Xango_iBonus.pdf", asset_type: "document")
#asset_35 = Asset.create(title: "Comparte y Ahorra", description: "Generales del Programa", author: "Xango", source: "document_Xango_Comparte_y_ahorra.pdf", asset_type: "document")
asset_36 = Asset.create(title: "Edificar Promover", description: "Presentación utilizada en la 1a. Convención IUVARE 2011", author: "Marisa Dodero", source: "document_Marisa_Dodero_Edificar_Promover.pdf", asset_type: "document")
#asset_37 = Asset.create(title: "Customer connect FAQ", description: "Generales del programa", author: "Xango", source: "document_Xango_Customer_conect_FAQ.pdf", asset_type: "document")
asset_38 = Asset.create(title: "Organización de tiempo", description: "Presentación de Jorge Arzamendi en la 1a. Convención IUVARE 2011", author: "Jorge Arzamendi", source: "document_Jorge_Arzamendi_Organizacion_del_tiempo.pdf", asset_type: "document")
asset_39 = Asset.create(title: "Libertad Financiera", description: "Presentación de Circe Rodríguez en la 1a. Convención IUVARE 2011", author: "Circe Rodríguez", source: "document_Circe_Rodriguez_Libertad_Financiera.pdf", asset_type: "document")
asset_40 = Asset.create(title: "Yo Creador Absoluto", description: "Presentación de Estela Salinas durante el seminario de junio  de 2012", author: "Estela Salinas", source: "document_Estela_Salinas_Yo_creador_absoluto.pdf", asset_type: "document")
asset_41 = Asset.create(title: "Averiguación FORM", description: "Averiguación FORM", author: "Iuvare", source: "document_Iuvare_Averiguacion_FORM.pdf", asset_type: "document")
asset_42 = Asset.create(title: "Seguimiento", description: "Presentación de Jorge Arzamendi en el seminario de agosto de 2011", author: "Jorge Arzamendi", source: "document_Jorge_Arzamendi_Seguimiento.pdf", asset_type: "document")
asset_43 = Asset.create(title: "El sueño", description: "Presentacion de Estela Salinas en el seminario de agosto de 2011", author: "Estela Salinas", source: "document_Estela_Salinas_El_sueno.pdf", asset_type: "document")
#asset_44 = Asset.create(title: "Entrevista Liz Salinas 200k", description: "Entrevista realizada por Xango a nuestra premier 200k Liz Salinas", author: "Xango", source: "document_Xango_Entrevista_a_Liz_Salinas_200k.pdf", asset_type: "document")
#asset_45 = Asset.create(title: "Configurar tu correo en Outlook", description: "Como configurar mi correo electronico con Outlook", author: "Iuvare", source: "document_Iuvare_Configurar_tu_correo_en_Outlook.pdf", asset_type: "document")
#asset_46 = Asset.create(title: "Mi Lista y Enviar el Plan", description: "Como enviar el plan de negocios por correo electronico", author: "Iuvare", source: "document_Iuvare_Enviar_el_plan_por_correo.pdf", asset_type: "document")
asset_47 = Asset.create(title: "Nuestro papel en el México de hoy", description: "Presentación de Jorge Arzamendi durante el seminario del 4 de febrero de 2012", author: "Jorge Arzamendi", source: "document_Jorge_Arzamendi_Nuestro_papel_en_el_mexico_de_hoy.pdf", asset_type: "document")
#asset_48 = Asset.create(title: "Priscilla Harrison", description: "Presentacion de Priscilla Harrison", author: "Iuvare", source: "document_iuvare_Priscilla_Harrison.pdf", asset_type: "document")

#asset_type = training
asset_49 = Asset.create(title: "Módulo 1", description: "Jorge Arzamendi imparte el Módulo 1", author: "Jorge Arzamendi", source: "training_Jorge_Arzamendi_Modulo_1", asset_type: "training", test_id: test_modulo_1)
asset_50 = Asset.create(title: "Módulo 2", description: "Circe Rodríguez imparte el Módulo 2", author: "Circe Rodríguez", source: "training_Circe_Rodriguez_Modulo_2", asset_type: "training", test_id: test_modulo_2)
asset_51 = Asset.create(title: "Módulo 3", description: "Liz Salinas imparte el Módulo 3", author: "Liz Salinas", source: "training_Liz_Salinas_Modulo_3", asset_type: "training", test_id: test_modulo_3)
#asset_52 = Asset.create(title: "Modulo 4", description: "Raul Villegas imparte el Modulo 4", author: "Raul Villegas", source: "training_Raul_Villegas_Modulo_4", asset_type: "training", test_id: test_modulo_4)
asset_53 = Asset.create(title: "Taller Plan de Compensación", description: "Samuel Beutelspacher imparte el taller de Plan de Compensación", author: "Samuel Beutelspacher", source: "training_Samuel_Beutelspacher_Taller_Plan_de_Compensacion", asset_type: "training", test_id: test_basics)
asset_54 = Asset.create(title: "Sesión de respuestas médicas(inglés)", description: "Sesión de respuestas médicas impartida por el Dr. Templeman (Convención IUVARE 2011)(INGLÉS)", author: "Dr Frederic Templeman", source: "training_Dr_Frederic_Templeman_Sesion_de_respuestas_medicas(ingles)", asset_type: "training")
#asset_55 = Asset.create(title: "Glimpse(ingles)", description: "Beverly Hollister Glimpse(ingles)", author: "Beverly Hollister", source: "training_Beverly_Hollister_Glimpse(ingles)", asset_type: "training")
asset_58 = Asset.create(title: "Planes de compensación", description: "Estela Salinas explica los diferentes planes de compensación", author: "Estela Salinas", source: "training_Estela_Salinas_Planes_de_compensacion", asset_type: "training")
asset_64 = Asset.create(title: "Reglas de IUVARE", description: "Liz Salinas explica las reglas de IUVARE.", author: "Liz Salinas", source: "training_Liz_Salinas_Reglas_de_iuvare", asset_type: "training")
#asset_65 = Asset.create(title: "La revolucion del bienestar", description: "La revolucion del bienestar", author: "Paul Zane Pilser", source: "training_Paul_Zane_Pilser_La_revolucion_del_bienestar", asset_type: "training")
#asset_66 = Asset.create(title: "Xango presentando a Estela Salinas", description: "Video producido por Xango presentando a Estela Salinas", author: "Estela Salinas", source: "training_Estela_Salinas_Xango_presentando_a_Estela_Salinas", asset_type: "training")
#asset_67 = Asset.create(title: "Capacitacion Priscilla Harrison", description: "Capacitacion Priscilla Harrison", author: "Priscilla Harrison", source: "training_Priscilla_Harrison_Capacitacion_Priscilla_Harrison", asset_type: "training")
#asset_68 = Asset.create(title: "Capacitacion Priscilla Harrison(ingles)", description: "Capacitacion Priscilla Harrison(ingles)", author: "Priscilla Harrison", source: "training_Priscilla_Harrison_Capacitacion_Priscilla_Harrison(ingles)", asset_type: "training")

#asset_type = convention
asset_57 = Asset.create(title: "Discurso de Aaron Garrity", description: "Discurso de Aaron Garrity", author: "Aaron Garrity", source: "convention_Aaron_Garrity_Discurso_de_Aaron_Garrity", asset_type: "convention")
asset_59 = Asset.create(title: "Xango", description: " ", author: "Joe Morton", source: "convention_Joe_Morton_Xango", asset_type: "convention")

asset_69 = Asset.create(title: "Convención Iuvare 2011", description: "El fundador Aaron Garrity en la convención IUVARE 2011", author: "Aaron Garrity", source: "convention_Aaron_Garrity_Convencion_Iuvare_2011", asset_type: "convention")
#asset_70 = Asset.create(title: "Convencion iuvare 2012 pt1", description: "Daniel Hernandez durante la convencion iuvare 2012", author: "Daniel Hernandez", source: "convention_Daniel_Hernandez_Convencion_Iuvare_2012_pt1", asset_type: "convention")
#asset_71 = Asset.create(title: "Convencion iuvare 2012 pt2", description: "Daniel Hernandez cuenta su historia durante la convencion iuvare 2012", author: "Daniel Hernandez", source: "convention_Daniel_Hernandez_Convencion_Iuvare_2012_pt2", asset_type: "convention")
asset_72 = Asset.create(title: "Experiencia con Xango", description: "El Dr Arturo Arenas nos platica su experiencia con Xango", author: "Dr Arturo Arenas", source: "convention_Dr_Arturo_Arenas_Experiencia_con_Xango", asset_type: "convention")
asset_73 = Asset.create(title: "Experiencia con Xango(inglés)", description: "El Dr Frederic Templeman nos platica su experiencia con Xango", author: "Dr Frederic Templeman", source: "convention_Dr_Frederic_Templeman_Experiencia_con_Xango(ingles)", asset_type: "convention")
asset_74 = Asset.create(title: "Convención IUVARE 2011", description: "Gordon Morton durante la convención IUVARE 2011", author: "Gordon Morton", source: "convention_Gordon_Morton_Convencion_Iuvare_2011", asset_type: "convention")
asset_75 = Asset.create(title: "Convención IUVARE 2012", description: "Estela Salinas durante la convención IUVARE 2012", author: "Estela Salinas", source: "convention_Estela_Salinas_Convencion_Iuvare_2012", asset_type: "convention")
asset_76 = Asset.create(title: "Convención IUVARE 2011", description: "Joe Morton durante la convención IUVARE 2011", author: "Joe Morton", source: "convention_Joe_Morton_Convencion_Iuvare_2011", asset_type: "convention")
asset_77 = Asset.create(title: "Convención IUVARE 2012", description: "Joe Morton durante la convención IUVARE 2012", author: "Joe Morton", source: "convention_Joe_Morton_Convencion_Iuvare_2012", asset_type: "convention")
asset_78 = Asset.create(title: "Convención IUVARE 2012", description: "Jorge Arzamendi durante la convención IUVARE 2012", author: "Jorge Arzamendi", source: "convention_Jorge_Arzamendi_Convencion_Iuvare_2012", asset_type: "convention")
asset_79 = Asset.create(title: "Convención IUVARE 2011", description: "Jorge Arzamendi nos enseña la importancia de la correcta administración del tiempo", author: "Jorge Arzamendi", source: "convention_Jorge_Arzamendi_Convencion_Iuvare_2011", asset_type: "convention")
asset_80 = Asset.create(title: "Convención IUVARE 2012", description: "Jorge Font durante la convencion iuvare 2012", author: "Jorge Font", source: "convention_Jorge_Font_Convencion_Iuvare_2012", asset_type: "convention")
asset_81 = Asset.create(title: "Convención IUVARE 2011(inglés)", description: "Kent Wood fundador de Xango nos enseña la importancia de ser diferentes", author: "Kent Wood", source: "convention_Kent_Wood_Convencion_Iuvare_2011(ingles)", asset_type: "convention")
asset_82 = Asset.create(title: "Convención IUVARE 2011", description: "Liz Salinas nos habla sobre el equilibrio en nuestra vida", author: "Liz Salinas", source: "convention_Liz_Salinas_Convencion_Iuvare_2011", asset_type: "convention")
asset_83 = Asset.create(title: "Convención IUVARE 2011", description: "Nuestra Premier 500k Estela Salinas en el cierre de la convención de fin de año IUVARE 2011", author: "Estela Salinas", source: "convention_Estela_Salinas_Convencion_Iuvare_2011", asset_type: "convention")

#asset_type = seminar
asset_62 = Asset.create(title: "Tailandia 2010 día uno", description: "Jorge Arzamendi Tailandia 2010 día uno", author: "Jorge Arzamendi", source: "seminar_Jorge_Arzamendi_Tailandia_2010_dia_uno", asset_type: "seminar")
asset_56 = Asset.create(title: "Tailandia 2010 día dos", description: "Circe Rodríguez Tailandia 2010 día dos", author: "Circe Rodríguez", source: "seminar_Circe_Rodriguez_Tailandia_2010_dia_dos", asset_type: "seminar")
asset_61 = Asset.create(title: "Tailandia 2010 día tres", description: "Raul Villegas Tailandia 2010 día tres", author: "Raul Villegas", source: "seminar_Raul_Villegas_Tailandia_2010_dia_tres", asset_type: "seminar")
asset_60 = Asset.create(title: "Tailandia 2010 día cuatro", description: "Liz Salinas Tailandia 2010 día cuatro", author: "Liz Salinas", source: "seminar_Liz_Salinas_Tailandia_2010_dia_cuatro", asset_type: "seminar")
asset_63 = Asset.create(title: "Tailandia 2010 día cinco", description: "Estela Salinas Tailandia 2010 día cinco", author: "Estela Salinas", source: "seminar_Estela_Salinas_Tailandia_2010_dia_cinco", asset_type: "seminar")

asset_84 = Asset.create(title: "Seminario febrero 2012", description: "Circe Rodríguez Premier 100k nos muestra un método práctico para lograr la libertad financiera ", author: "Circe Rodríguez", source: "seminar_Circe_Rodriguez_Seminario_febrero_2012", asset_type: "seminar")
asset_85 = Asset.create(title: "La cornada al león", description: "Enrique Flores “La cornada al león” Seminario de julio de 2014", author: "Enrique Flores", source: "seminar_Enrique_Flores_La_cornada_al_leon", asset_type: "seminar")
asset_86 = Asset.create(title: "Seminario octubre 2011 pt1", description: "Guillermo Ganem en el seminario IUVARE de octubre de 2011 (Parte 1)", author: "Guillermo Ganem", source: "seminar_Guillermo_Ganem_Seminario_octubre_2011_pt1", asset_type: "seminar")
asset_87 = Asset.create(title: "Seminario octubre 2011 pt2", description: "Guillermo Ganem en el seminario IUVARE de octubre de 2011 (Parte 2)", author: "Guillermo Ganem", source: "seminar_Guillermo_Ganem_Seminario_octubre_2011_pt2", asset_type: "seminar")
asset_88 = Asset.create(title: "Seminario marzo 2013", description: "Estela Salinas durante el seminario de marzo de 2013", author: "Estela Salinas", source: "seminar_Estela_Salinas_Seminario_marzo_2013", asset_type: "seminar")
asset_89 = Asset.create(title: "Seminario post-regional 2010", description: "Joe Morton durante el seminario post-regional 2010", author: "Joe Morton", source: "seminar_Joe_Morton_Seminario_post-regional_2010", asset_type: "seminar")

asset_90 = Asset.create(title: "Seminario marzo 2013", description: "Jorge Arzamendi durante el seminario de marzo de 2013", author: "Jorge Arzamendi", source: "seminar_Jorge_Arzamendi_Seminario_marzo_2013", asset_type: "seminar")
asset_91 = Asset.create(title: "Seminario febrero 2012", description: "Jorge Arzamendi Premier 100k de IUVARE durante el seminario de febrero 2012", author: "Jorge Arzamendi", source: "seminar_Jorge_Arzamendi_Seminario_febrero_2012", asset_type: "seminar")
#asset_92 = Asset.create(title: "La vida como debe ser", description: "Massimo del Moro La vida como debe ser", author: "Massimo del Moro", source: "seminar_Massimo_del_Moro_La_vida_como_debe_ser", asset_type: "seminar")
asset_93 = Asset.create(title: "Seminario mayo 2012", description: "Premier 100k Marisa Dodero durante su seminario en mayo 2012", author: "Marisa Dodero", source: "seminar_Marisa_Dodero_Seminario_mayo_2012", asset_type: "seminar")
asset_94 = Asset.create(title: "Seminario enero 2012 pt1", description: "Primera parte del Seminario de Enrique Flores (8 de enero 2012)", author: "Enrique Flores", source: "seminar_Enrique_Flores_Seminario_enero_2012_pt1", asset_type: "seminar")
asset_95 = Asset.create(title: "El árbol rojo del multinivel pt1", description: "El árbol rojo del multinivel (Parte 1)", author: "Mario Rodríguez Padres", source: "seminar_Mario_Rodriguez_Padres_El_arbol_rojo_del_multinivel_pt1", asset_type: "seminar")
asset_96 = Asset.create(title: "El árbol rojo del multinivel pt2", description: "El árbol rojo del multinivel (Parte 2)", author: "Mario Rodríguez Padres", source: "seminar_Mario_Rodriguez_Padres_El_arbol_rojo_del_multinivel_pt2", asset_type: "seminar")
asset_97 = Asset.create(title: "Yo creador absoluto", description: "Seminario impartido por Estela Salinas en junio de 2012", author: "Estela Salinas", source: "seminar_Estela_Salinas_Yo_creador_absoluto", asset_type: "seminar")
asset_98 = Asset.create(title: "Seminario marzo 2012 pt1", description: "Seminario impartido por Ron White durante el mes de marzo de 2012 (Parte 1)", author: "Ron White", source: "seminar_Ron_White_Seminario_marzo_2012_pt1", asset_type: "seminar")
asset_99 = Asset.create(title: "Seminario marzo 2012 pt2", description: "Seminario impartido por Ron White durante el mes de marzo de 2012 (Parte 2)", author: "Ron White", source: "seminar_Ron_White_Seminario_marzo_2012_pt2", asset_type: "seminar")
asset_100 = Asset.create(title: "El precio del éxito no es negociable", description: "Liza Cortés El precio del éxito no es negociable", author: "Liza Cortes", source: "seminar_Liza_Cortes_El_precio_del_exito_no_es_negociable", asset_type: "seminar")
asset_101 = Asset.create(title: "AMG", description: "Astrid de Esesarte y Leo Ayala AMG septiembre 2014", author: "Astrid y Leo", source: "seminar_Astrid_y_Leo_AMG", asset_type: "seminar")
asset_102 = Asset.create(title: "Historia", description: "Astrid de Esesarte y Leo Ayala cuentan su historia septiembre 2014", author: "Astrid y Leo", source: "seminar_Astrid_y_Leo_Historia", asset_type: "seminar")
asset_102_01 = Asset.create(title: "La vida es una fiesta", description: "Seminario de Marina Buzali", author: "Marina Buzali", source: "seminar_Marina_Buzali_La_vida_es_una_fiesta", asset_type: "seminar")
asset_102_02 = Asset.create(title: "Hecho en IUVARE", description: "Seminario de Israel Galván", author: "Israel Galván", source: "seminar_Israel_Galvan_Hecho_en_iuvare", asset_type: "seminar")

#asset_type = plan
asset_103 = Asset.create(title: "Plan Jorge Arzamendi", description:"Plan de negocios presentado por Jorge Arzamendi", author:"Jorge Arzamendi", source: "plan_Jorge_Arzamendi_Plan_Jorge_Arzamendi", asset_type: "plan", test_id: test_plan.id)
asset_104 = Asset.create(title: "Plan Jorge Arzamendi Colombia", description:"Plan de negocios para Colombia presentado por Jorge Arzamendi", author:"Jorge Arzamendi", source: "plan_Jorge_Arzamendi_Plan_Jorge_Arzamendi_Colombia", asset_type: "plan", test_id: test_plan.id)
asset_105 = Asset.create(title: "Plan Circe Rodríguez", description:"Plan de negocios presentado por Circe Rodríguez", author:"Circe Rodríguez", source: "plan_Circe_Rodriguez_Plan_Circe_Rodriguez", asset_type: "plan", test_id: test_plan.id)
asset_106 = Asset.create(title: "Plan Circe Rodriguez Colombia", description:"Plan de negocios para Colombia presentado por Circe Rodríguez", author:"Circe Rodríguez", source: "plan_Circe_Rodriguez_Plan_Circe_Rodriguez_Colombia", asset_type: "plan", test_id: test_plan.id)
asset_107 = Asset.create(title: "Plan Enrique Flores", description:"Plan de negocios presentado por Enrique Flores", author:"Enrique Flores", source: "plan_Enrique_Flores_Plan_Enrique_Flores", asset_type: "plan", test_id: test_plan.id)

#asset_type = FAQ
asset_108 = Asset.create(title: "FAQ", description:"Documento PDF del FAQ", author:"FAQ", source: "FAQ.pdf", asset_type: "FAQ")

#Sedes
sede_1 = Office.create(name: "Morelia", address: "Leon Guzman 78, Col. Centro", latitude: "19.704424", longitude: "-101.196846", description: "", schedule: "Plan: Lunes a viernes 8:00pm")
sede_2 = Office.create(name: "México - El Ruedo", address: "Augusto Rodin #110 Esq. Maximino Ávila Camacho. Col. Ciudad de los deportes", latitude: "19.3838687", longitude: "-99.1807992", description: "", schedule: "Plan: Lunes a Viernes 6:00pm 8:00pm y Sábado 9:00am")
sede_3 = Office.create(name: "Guadalajara", address: "Plaza Bonita local sub ancla 1, Av. México 3370, Monraz, CP 44670", latitude: "20.678718", longitude: "-103.402447", description: "", schedule: "Plan: Lunes a Viernes 10:00am, 6:00pm, 8:00pm y Sábado 10:00am")
sede_4 = Office.create(name: "Toluca", address: "Heriberto Enríquez 361 LT 201 Col. Real de San Javier, Metepec", latitude: "19.262383", longitude: "-99.644541", description: "", schedule: "Plan: Lunes 10:30am, Miércoles 10:00am, Sábado 9:00am, Lunes a Viernes 7:00pm")
sede_5 = Office.create(name: "Querétaro", address: "Ejército Republicano 139 Int. 104 Col. Carretas", latitude: "20.5892049", longitude: "-100.3731074", description: "", schedule: "Plan: Martes y Jueves 8:00pm, Sábado 10:00am")
#sede_6 = Office.create(name: "México - Big Ben", address: "Cerro de las Campanas No. 3 Torre 1 Piso 6 Edi. Big Ben Col. San Andrés Atenco Tlalnepantla, Edo. de México.", latitude: "19.5413723", longitude: "-99.2148748", description: "", schedule: "Plan: Miércoles 8:00pm")
sede_7 = Office.create(name: "México - Corporativo", address: "Corporativo Nápoles Av. Insurgentes Sur 863 Piso 1 Col. Nápoles", latitude: "19.3881774", longitude: "-99.1748896", description: "", schedule: "Plan: Martes y Jueves 10:00am")
sede_8 = Office.create(name: "Tepic", address: "Prisciliano Sánchez 232. Colonia San Antonio", latitude: "21.501437", longitude: "-104.89028", description: "", schedule: "Plan: Lunes a Viernes 8:00pm")
#sede_9 = Office.create(name: "Pto. Vallarta", address: "Milán 327 1er piso Col. La Vena", latitude: "20.6334622", longitude: "-105.2239167", description: "", schedule: "")
sede_10 = Office.create(name: "León", address: "Blvd. San Pedro 310 Col. San Isidro", latitude: "21.100674", longitude: "-101.6462318", description: "", schedule: "Plan: miércoles 7pm (los demás días con video del plan)")
#sede_11 = Office.create(name: "Puebla", address: "Av. Juárez #1905 4to piso oficina 13 Col. La Paz", latitude: "19.0496801", longitude: "-98.2141658", description: "", schedule: "")

#Historic Asset

ha_audios_1 = HistoricAsset.create(historic_asset_type: "audio",description: '

<div><ul><li>COC 218: "Influencia" - Enrique Flores</li><li>COC 217: "Razonamientos y reflexiones" - Benjamín Hernández</li><li>COC 216: "Enfrenta tus miedos" - Raúl Villegas</li><li>COC 215: "Iuvare: trabajo en equipo" -Elizabeth Salinas</li><li>COC 214: "Alquimistas de vida" - Berenice Garfias</li><li>COC 213: "Un mundo mejor" - Circe Rodríguez</li><li>COC 212: "Los zapatos rojos" - Gabriela Villagómez</li><li>COC 211: "Rotitos" - Estela Salinas<br></li></ul><ul><li>COC 210: "Un camino de libertad" - Laura Bayardo</li><li>COC 209: "El sistema te cambia la vida" - Javier Vélez</li><li>COC 208: "Los juegos del éxito, Parte 2" - Denisse Ducoing</li><li>COC 207: "Los juegos del éxito, Parte 1" - Denisse Ducoing</li><li>COC 206: "Tercer acto, se abre el telón" - Angélica Bautista</li><li>COC 205: "Comparte la visión de libertad" - Lina Nayeli Sánchez</li><li>COC 204: "Sueña en grande y acciona con el corazón" - Enrique Poblete</li><li>COC 203: "Entre el arroyo y la piedra" - Diego Emerith</li><li>COC 202: "Tandem" - Raúl Villegas</li><li>COC 201: "7 claves fundamentales del sistema Favao" - Samantha Barocio</li></ul><ul><li>COC 200: "Paradigmas" - Estela Salinas</li><li>COC 199: "Un día éramos 3, hoy 8000" - Jorge Andrés Arzamendi</li><li>COC 198: "Taller de ventas" - Margot Fernández</li><li>COC 197: "Repetición, te va a crear un grupo de gente" - Louis Carrillo</li><li>COC 196: "Cómplices de éxito" - Alejandro Bautista</li><li>COC 195: "¿Qué significa tu nombre?" - Daniel Hernández</li><li>COC 194: "El libro de mi vida" - Elizabeth Salinas</li><li>COC 193: "Convenciendo a los enanos" - Luis Costa</li><li>COC 192: "Hecho en Iuvare" - Israel Galván</li><li>COC 191: "El poder de servir" - Eduardo Barreto</li></ul><ul><li>COC 190: "Enfócate en tu sueño" - Daniel Hernández</li><li>COC 189: "El proceso de cerrar" - Circe Rodríguez</li><li>COC 188: "Responsabilidad" - Israel Galván</li><li>COC 187: "Siempre es la misma historia..." - Estela Salinas</li><li>COC 186: "Xango, el mejor modelo de negocio" - Joel Cruz</li><li>COC 185: "Bienvenida" - Estela Salinas</li><li>COC 184: "¿Quién ya tiene su ciclo?" - Rodrigo Villegas</li><li>COC 183: "Este negocio es para toda la vida" Carlos y Jazmín Jurado</li><li>COC 182: "El éxito no llega por casualidad" - Andrés Rodríguez</li><li>COC 181: "El Buda de Oro" - Elizabeth Salinas</li></ul><ul><li>COC 180: "Nuestra Maestría" - Astrid y Leo Ayala</li><li>COC 179: "Líderes del Network Marketing" - Circe Rodríguez</li><li>COC 178: "AMG" - Astrid y Leo Ayala</li><li>COC 177: "Libre al fin" - Jorge Andrés Arzamendi</li><li>COC 176: "Nuestra Visión Iuvare" - Premiers Iuvare (Circe, Liz y Ángel)</li><li>COC 175: "La Cornada al León" - Enrique Flores (¡ATACAR!)</li><li>COC 174: "Poder personal Parte 2" - Iván Vélez</li><li>COC 173: "Poder personal" - Iván Vélez</li><li>COC 172: "Hay días que cambian tu vida para siempre" - Margot Fernández</li><li>COC 171: "Sé feliz y exitoso" - Samuel Beutelspacher</li></ul><ul><li>COC 170: "La importancia de un seminario" - Fernando y Graciela García</li><li>COC 169: "Esta es tu convención" - Estela Salinas</li><li>COC 168: "Perseverancia y decisión" - Gabriel Torres</li><li>COC 167: "Esta foto se la debo a Xango" - Rossana Arau</li><li>COC 166: "Compromiso" - Gracia Abarca</li><li>COC 165: "Tu edad no define el tamaño de tus sueños" - Juan Corona</li><li>COC 164: "Deseo, restricción y certeza" - Pamela Monroy</li><li>COC 163: "El fracaso no es una opción" - Juan Carlos Luengo</li><li>COC 162: "¿Por qué nosotros estamos aquí" - Estela Salinas</li><li>COC 161: "¿De qué tamaño quieres tu mundo? - Circe Rodríguez</li></ul><ul><li>COC 160: "Atrévete a decidir y confiar en tu corazón" - Ixchel López</li><li>COC 159: "Prioridades" - Ángel Ortega</li><li>COC 158: "¿Cuál es tu misión de vida?" - Juan Carlos Maldonado</li><li>COC 157: "Convertirme en el mejor" - Astrid de Esesarte</li><li>COC 156: "Fórmula de poder" - Joel Cruz</li><li>COC 155: "10 objeciones" - Liza Cortés</li><li>COC 154: "Libros, seminarios y convenciones" - Premiers Iuvare (Ángel, Iván y Estela)</li><li>COC 153: "Herramientas de auspicio y comercialización" - Premiers Iuvare (Circe, Liz y Jorge)</li><li>COC 152: "Un reto para el futuro" - Luis Costa</li><li>COC 151: "Edificación" - Jorge Andrés Arzamendi</li></ul><ul><li>COC 150: "Cómo lograr lo que te propones" - Samuel Beutelspacher</li><li>COC 149: "Sistema Favao" - Marilú Almazán</li><li>COC 148: "¿De qué color eres tu" - Estela Salinas</li><li>COC 147: "Utiliza el sistema" - Luis Costa</li><li>COC 146: "Aprende a modelar la excelencia" - Daniel Hernández</li><li>COC 145: "Cómo alcanzar lo que quieres en la vida" - Rigoberto Romanillo</li><li>COC 144: "Network marketing: una nueva profesión" - Jorge Andrés Arzamendi</li><li>COC 143: "Y...uno crece" - María Teresa Álvarez</li><li>COC 142: "Hemos nacido para triunfar" - Luis Costa</li><li>COC 141: "El éxito tiene una fórmula" - Dr. Lair Ribeiro</li></ul><ul><li>COC 140: "Abandona tu zona de confort" - Ángel Ortega</li><li>COC 139: "Los doce coladores" - Estela Salinas</li><li>COC 138: "Enfrenta tus retos" - Francisco Rodríguez</li><li>COC 137: "Claridad es poder" - Laura Filoteo</li><li>COC 136: "Ganar es lo único" - Marina Buzali</li><li>COC 135: "El seguimiento" - Jorge Andrés Arzamendi</li><li>COC 134: "Rompiendo paradigmas" - Sonia Sabre y Héctor Romero</li><li>COC 133: "Los estándares del éxito" - Iván Vélez</li><li>COC 132: "De empleada a emprendedora" - Marlene Rodríguez</li><li>COC 131: "El arte de contactar" - Daniel Hernández</li></ul><ul><li>COC 130: "El sistema es la clave de tu éxito" - Ángel Ortega</li><li>COC 129: "Líderes empresarios" - María Teresa Álvarez</li><li>COC 128: "10 principios básicos" - Francisco Rodríguez</li><li>COC 127: "Esa noche" - Eduardo Barreto</li><li>COC 126: "Certeza en ti" - Gabriel Grimaldi</li><li>COC 125: "Lo que esta industria hace por ti" - Rodrigo Villegas</li><li>COC 124: "Automotivación es la clave" - Astrid y Leo Ayala</li><li>COC 123: "Las coincidencias no existen" - Alfonso Perea</li><li>COC 122: "¿Qué estoy haciendo con mi vida?" - Jesús Sanabria</li><li>COC 121: "Cambia tu enfoque" - Grisel Samaniego</li></ul><ul><li>COC 120: "El canto de las sirenas" - Joel Cruz</li><li>COC 119: "Coherencia" - Elizabeth Salinas</li><li>COC 118: "Sin protestar" - Iván y Millie Morales</li><li>COC 117: "Explota el líder que hay en ti" - Iván Vélez</li><li>COC 116: "Talento vs habilidad" - Salomon Hernández</li><li>COC 115: "El sueño" - Estela Salinas</li><li>COC 114: "Definiendo una identidad, construyendo una visión" - Israel Galván</li><li>COC 113: "El efecto pigmalión" - Estela Alvarado</li><li>COC 112: "El águila" - Fernando y Regi Olivar</li><li>COC 111: "De qué vas a vivir" - Braulio Filoteo</li></ul><ul><li>COC 110: "Creando restricción" - Pamela Monroy</li><li>COC 109: "El mayor riesgo es no hacerlo" - Samuel Beutelspacher</li><li>COC 108: "El camino heroico de todo líder, Parte 2" - Circe Rodríguez</li><li>COC 107: "El camino heroico de todo líder, Parte 1" - Circe Rodríguez</li><li>COC 106: "Trabajo en equipo" - Ana Laura Mondragón</li><li>COC 105: "Equilibrio" - Liz Salinas</li><li>COC 104: "Utiliza tus cinco sentidos" - Daniel Hernández</li><li>COC 103: "Mantén tu mente limpia y alimentala " - Iván Morales</li><li>COC 102: "Tu beneficio está en el beneficio de los demás" - Luis Costa</li><li>COC 101: "¡En sus marcas!, ¡Listos!...¿Listos?" - Jorge Andrés Arzamendi</li></ul><ul><li>COC 100: "Soy un hombre común" - Juan Carlos Ruíz</li><li>COC 099: "Expansión y desfase" - Ángel Ortega</li><li>COC 098: "Compañía, Producto y Negocio" - Gordon Morton</li><li>COC 097: "El sistema no es negociable" - Estela Salinas</li><li>COC 096: "Toma una decisión" - Raúl Villegas</li><li>COC 095: "El secreto está en los cimientos" - Eduardo Barreto</li><li>COC 094: "Algunos principios que nos han ayudado" - Luis Costa</li><li>COC 093: "Taller de Cierre" - Ivan Vélez</li><li>COC 092: "El que cree lo puede lograr" - Terri e Ivon McEwen</li><li>COC 091: "Vamos a hablar de realidades" - Liza Cortés</li></ul><ul><li>COC 090: "El ser y el hacer" - Luis Costa, Iván Morales y Pedro Lizardi</li><li>COC 089: "El Árbol Rojo del Multinivel, Parte 2" - Mario Rodríguez Padrés</li><li>COC 088: "El Árbol Rojo del Multinivel, Parte 1" - Mario Rodríguez Padrés</li><li>COC 087: "Mi Historia" - Estela Salinas</li><li>COC 086: "Los Próximos 10 Años" - Priscilla Harrison</li><li>COC 085: "Libertad Financiera" - Circe Rodríguez</li><li>COC 084: "Cómo construir una organización" - Kenny Stewart</li><li>COC 083: "Administración del tiempo" - Jorge Andrés Arzamendi</li><li>COC 082: "Alimenta tus sueños" - Iván Vélez</li><li>COC 081: "Sé el dueño de tu vida" - Estela Salinas</li></ul><ul><li>COC 080: "Es cuestión de perseverancia" - Suzi Jackson</li><li>COC 079: "Reprograma tu computadora" - Tommy Johnson</li><li>COC 078: "Tu manera de ver las cosas hace que las cosas cambien" - Estela Salinas</li><li>COC 077: "No podíamos ser los únicos con un sueño" - Tino y Marilo Cabrera</li><li>COC 076: "De cero al escenario" - Jorge Andrés Arzamendi</li><li>COC 075: "Busca otro como tu" - Eduardo Barreto</li><li>COC 074: "Personas ordinarias haciendo algo extraordinario" - Luis Costa</li><li>COC 073: "20 llaves de productividad" - Estela Alvarado</li><li>COC 072: "Todos tenemos un cartucho de dinamita" - Tony y Wilda Morales</li><li>COC 071: "No hay crisis, sólo cambios" - Pedro Valdecanto</li></ul><ul><li>COC 070: "De adentro hacia afuera" - Enrique Flores</li><li>COC 069: "Aprender, crecer y cambiar" - Fernando y Regi Olivar</li><li>COC 068: "Tu mejor tú" - Joaquín y Marian Lucas</li><li>COC 067: "7 leyes universales" - Estela Salinas</li><li>COC 066: "Ajustando el vuelo" - Marisa Dodero</li><li>COC 065: "Desafiando mi potencial" - Rodrigo Sepúlveda</li><li>COC 064: "Las personas llegan a tu vida por una razón" - Liza Cortés</li><li>COC 063: "Sentido común y creatividad" - Alfredo López y Lilia del Rayo</li><li>COC 062: "Vuelve a soñar" - Daniel Hernández</li><li>COC 061: "Reconocimiento, recompensa y esperanza" - Ángel Ortega</li></ul><ul><li>COC 060: "10 preguntas para un empresario" - Ramón y María Teresa Gutiérrez</li><li>COC 059: "Paga, el precio es barato" - José Luis y Flora Romero</li><li>COC 058: "¿A qué se dedican ustedes?" - Bill Hawkings</li><li>COC 057: "Vamos a llegar muy lejos" - Estela Salinas</li><li>COC 056: "Lo que vale la pena encontrar vale la pena buscar" - Enrique Flores</li><li>COC 055: "El sueño genera energía" - Luis Costa</li><li>COC 054: "Hábitos" - Berc Gulick</li><li>COC 053: "Nuestro papel en el México de hoy" - Jorge Andrés Arzamendi</li><li>COC 052: "Los límites no existen, son autoimpuestos" - Daniel y Angélica Hernández</li><li>COC 051: "Shhhh!!!" - Circe Rodríguez</li></ul><ul><li>COC 050: "Hay dos cosas que tú controlas" - Roberto y Loli Ritchie</li><li>COC 049: "Hay muchas maneras de ser libre" - Pedro Lizardi</li><li>COC 048: "Todo comienza con una decisión" - Ivan Velez</li><li>COC 047: "El precio del éxito no es negociable" - Liza Cortés</li><li>COC 046: "La vida como debe ser" - Massimo del Moro</li><li>COC 045: "Lo importante no es lo que ganas, sino en quién te conviertes" - Osvaldo Ramírez</li><li>COC 044: "Afuera hay muchos esperando entrar" - Ivan y Millie Morales</li><li>COC 043: "La oportunidad de mi vida" - Joaquín y Marian Lucas</li><li>COC 042: "De nada sirve la técnica si no hay perro" - Sergio Rivera</li><li>COC 041: "Hoy es un buen día para empezar" - Lilan Davis</li></ul><ul><li>COC 040: "Una decisión, un evento, cambió mi vida" - Aldonza Velez</li><li>COC 039: "Megacualidades de los triunfadores" - Marina Buzali</li><li>COC 038: "Lo grande que puedes llegar a ser" - Raúl Villegas</li><li>COC 037: "Cabeza dura" - Loule y Kathy Carrillo</li><li>COC 036: "La verdad a veces duele" - Ken y Donna Stewart</li><li>COC 035: "Aférrate a ese sueño" - Luis Costa</li></ul><p>Audios Viejos Iuvare</p><ul><li>COC 036: "Lo bueno es enemigo de lo mejor" - Enrique Flores</li><li>COC 035: "Principios de liderazgo" - Raúl Villegas</li><li>COC 033: "Xango se hace con un gran sueño" - Roberto Flores</li><li>COC 032: "Cambia tu estilo de vida" - Marcela Flores</li><li>COC 031: "El crossline" - Jorge Andrés Arzamendi</li><li>COC 030: "Simplifica tu negocio" - Circe Rodríguez</li><li>COC 029: "El proceso del éxito" - Alexis Budd</li><li>COC 026: "El momento perfecto es ¡ahora!" - Alexis Budd</li><li>COC 025: "Eres extra o protagonista" - Jorge Andrés Arzamendi</li><li>COC 024: "El empresario" - Iván Morales</li></ul><ul><li>COC 022: "8 libros recomendados" - Jorge Andrés Arzamendi</li><li>COC 020: "Una oportunidad de negocio" - Raúl Galindo</li><li>COC 017: "Una segunda oportunidad" - Raúl y Rocío Galindo</li><li>COC 016: "Cómo generar riqueza" - Raúl y Rocío Galindo</li><li>COC 014: "Buscando el colorín" - Estela Salinas</li><li>COC 011: "Los nuevos profesionales del NM" - Raúl y Rocío Galindo</li><li>COC 010: "Manejo de objeciones" - Enrique Flores</li><li>COC 005: "La lista del miedo" - Marco Galbiati</li><li>COC 003: "Básicos 2" - Estela Salinas</li><li>COC 002: "Básicos" - Estela Salinas</li><li>COC 001: "Sé el dueño de tu vida" - Estela Salinas</li></ul><ul><li>COC XXX: "Atrévete, cambia" - Circe Rodríguez</li><li>COC XXX: "El cierre" - Marco Galbiati</li><li>COC XXX: "La lista del miedo" - Marco Galbiati</li><li>COC XXX: "De amateur a profesional en NM" - Enrique Flores</li><li>COC XXX: "Toma acción" - Marcela Flores</li><li>COC XXX: "El secreto de un millón de dólares" - David Butler</li><li>COC XXX: "La varita mágica" - Sherman Unkefer</li><li>COC XXX: "Mangostán, el factor X" - Dr. Templeman</li><li>COC XXX: "Conviértete en líder" - Roberto Re</li><li>COC XXX: "Construya su red de mercadeo" - Jim Rohn</li></ul><p>Audios AMMIM</p><ul><li>"Mangostán: un súper antioxidante" - Dra. Angelita Martín Ferreira</li><li>"Salud y bienestar con mangostán" - Dra. Angelita Martín Ferreira</li></ul><br><p>Training pack: Jorge Andrés Arzamendi</p><br><p>Kit de inicio 2012 10 Audios de Capacitación Básica:</p><ul><li>COC 011: "Placer y dolor" - Estela Salinas</li><li>COC 009: "Una magnífica opción ante la crisis" - Jorge Andrés Arzamendi</li><li>COC 008: "La importancia de tener un sueño" - Elizabeth Salinas</li><li>COC 007: "¿Por qué un collage" - Estela Salinas</li><li>COC 006: "Las reglas del juego" - Estela Salinas</li><li>COC 005: "Excusas y Creencias" - Enrique Flores</li><li>COC 004: "Cómo contactar" - Jorge Andrés Arzamendi</li><li>COC 003: "Cambia tu estilo de vida" - Marcela Flores</li><li>COC 002: "Buscando el Colorín" - Estela Salinas</li><li>COC 001: "Lo mejor que me pudo pasar" - Elizabeth Salinas</li></ul><p>Kit de inicio 2013 10 Audios de Capacitación Básica:</p><ul><li>COC 010: "Las reglas del juego" - Estela Salinas</li><li>COC 009: "Ajustando el vuelo" - Marisa Dodero</li><li>COC 008: "¿Por qué un collage" - Estela Salinas</li><li>COC 007: "¿Placer y dolor?" - Estela Salinas</li><li>COC 006: "Lo mejor que me pudo pasar" - Elizabeth Salinas</li><li>COC 005: "Excusas y Creencias" - Enrique Flores</li><li>COC 004: "Nuestro papel en el México de hoy" - Jorge Andrés Arzamendi</li><li>COC 003: "La importancia de tener un sueño" - Elizabeth Salinas</li><li>COC 002: "Shhhhh!" - Circe Rodríguez</li><li>COC 001: "Como contactar" - Jorge Andrés Arzamendi</li></ul><p>Kit de inicio 2014 y 2015</p><ul><li>COC 010: "Las reglas del juego" - Estela Salinas</li><li>COC 009: "Ajustando el vuelo" - Marisa Dodero</li><li>COC 008: "¿Por qué un collage?" - Estela Salinas</li><li>COC 007: "¿De qué color eres tu?" - Estela Salinas</li><li>COC 006: "Lo mejor que me pudo pasar" - Elizabeth Salinas</li><li>COC 005: "Excusas y creencias" - Enrique Flores</li><li>COC 004: "Nuestro papel en el México de hoy" - Jorge Andrés Arzamendi</li><li>COC 003: "La importancia de tener un sueño" - Elizabeth Salinas</li><li>COC 002: "Creando restricción" - Pamela Monroy</li><li>COC 001: "Cómo contactar" - Jorge Andrés Arzamendi</li></ul><br></div>
')

ha_books_1 = HistoricAsset.create(historic_asset_type: "book",description: '
<div><p>2015<br></p><ol><li>Caldo de pollo para el alma - Canfield y Hansen</li><li>El vendedor más grande del mundo - Og Mandino</li><li>Ser, hacer y tener - Michel Domit</li><li>Los 7 hábitos de la gente altamente efectiva - Stephen Covey</li><li>Tu puedes sanar tu vida - Louise Hay</li><li>Sincrodestino - Deepak Chopra</li><li>La comunicación eficaz - Dr. Lair Ribeiro</li><li>Liderazgo: el poder de la inteligencia emocional - Daniel Goleman</li></ol><p><br></p>2014<br><ol><li>Despertando al gigante interior - Anthony Robbins</li><li>El secreto - Rhonda Byrne</li><li>Después del día diez - Carlitos Páez</li><li>El líder que no tenía cargo - Robin Sharma</li><li>Morir para ser yo - Anita Moorjani</li><li>Ensanchar la vida - Jorge Font</li><li>El hombre más rico de Babilonia - George S. Clason</li><li>Por favor sea feliz - Andrew Matthews</li><li>Vendedores Perros - Blair Singer</li></ol><br>2013<br><ol><li>Nos veremos en la cumbre - Zig Ziglar</li><li>Colorín colorado, este cuento, ¡no se ha acabado! - Odín Dupeyrón</li><li>Fracasar o triunfar: tu elección - Daniel Hernández</li><li>Mi primer millón - Charles Albert Poissant y Christian Godefroy</li><li>La ciencia de hacerse rico - Wallace D. Wattles</li><li>7 estrategias para alcanzar riqueza y felicidad - Jim Rohn</li><li>La matriz divina - Greg Braden</li><li>El toque de Midas - Robert Kiyosaki y Donald Trump</li><li>Fueras de serie - Malcolm Gladwell</li><li>Las 21 leyes irrefutables del liderazgo - John C. Maxwell</li><li>El negocio del siglo XXI - Robert Kiyosaki</li><li>El ABC para crear un equipo de negocios exitoso - Blair Singer</li></ol><br><p>2011 y 2012<br></p><ol><li>¿Quién se ha llevado mi queso? - Spencer Johnson</li><li>Piense y hágase rico - Napoleón Hill</li><li>Poder sin límites - Anthony Robbins</li><li>Los 7 hábitos de la gente altamente efectiva - Stephen Covey</li><li>Cuando para amar es tarde - Daniel Hernández</li><li>El árbol rojo del multinivel y las ventas directas - Mario Rodríguez Padrés</li><li>Libera tu carga - Estela Alvarado</li><li>Inteligencia emocional - Daniel Goleman</li><li>El poder de la intención - Wayne Dyer</li><li>Sincronicidad - Joseph Jaworski</li><li>Sobrevivir para contarlo - Immaculée Ilibagiza</li></ol></div>
')
